import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  output: "export",
  images: {
    unoptimized: true,
  },
  trailingSlash: true,
  reactStrictMode: true,
  poweredByHeader: false,
  async redirects() {
    return [
      { source: '/blog/sam-klar-gmo/', destination: '/podcast/sam-klar-gmo/', permanent: true },
      { source: '/blog/david-nicholas-x-funds/', destination: '/podcast/david-nicholas-x-funds/', permanent: true },
      { source: '/blog/bob-elliott-2/', destination: '/podcast/bob-elliott-unlimited-funds/', permanent: true },
      { source: '/blog/david-auerbach/', destination: '/podcast/david-auerbach-hoya-capital-homz-riet/', permanent: true },
      { source: '/blog/raymond-micaletti/', destination: '/podcast/raymond-micaletti-relative-sentiment-technologies-mood-etf/', permanent: true },
      { source: '/blog/sam-rahman-john-mcnamara/', destination: '/podcast/sam-rahman-john-mcnamara-hedgeye-asset-managment/', permanent: true },
      { source: '/blog/seth-cogswell/', destination: '/podcast/seth-cogswell-running-oak/', permanent: true },
      { source: '/blog/eric-lutton/', destination: '/podcast/eric-lutton-sound-income-strategies/', permanent: true },
      { source: '/blog/ryan-thomes/', destination: '/podcast/ryan-thomes-hotchkis-wiley/', permanent: true },
      { source: '/blog/kirk-mcdonald/', destination: '/podcast/kirk-mcdonald-argent-capital/', permanent: true },
      { source: '/blog/rob-thummel/', destination: '/podcast/rob-thummel-tortoise-capital/', permanent: true },
      { source: '/blog/bob-elliot/', destination: '/podcast/bob-elliott-unlimited-funds-2025/', permanent: true },
      { source: '/blog/brad-neuman/', destination: '/podcast/brad-neuman-alger/', permanent: true },
      { source: '/blog/wayne-penello/', destination: '/podcast/wayne-penello-nextgen-emp/', permanent: true },
      { source: '/blog/rob-harvey/', destination: '/podcast/rob-harvey-dfa/', permanent: true },
      { source: '/blog/clark-allen/', destination: '/podcast/clark-allen-horizon-investments/', permanent: true },
      { source: '/blog/paisley-nardini/', destination: '/podcast/paisley-nardini-simplify/', permanent: true },
      { source: '/blog/matt-kaufman/', destination: '/podcast/matt-kaufman-calamos/', permanent: true },
      { source: '/blog/jeff-cullen/', destination: '/podcast/jeff-cullen-schafer-cullen/', permanent: true },
      { source: '/blog/dan-petersen/', destination: '/podcast/dan-petersen-new-york-life/', permanent: true },
      { source: '/blog/kirsten-chang/', destination: '/podcast/kirsten-chang-vettafi/', permanent: true },
      { source: '/blog/adam-patti/', destination: '/podcast/adam-patti-vistashares/', permanent: true },
      { source: '/blog/emma-harper/', destination: '/podcast/emma-harper-sage-advisory/', permanent: true },
      { source: '/blog/rob-arnott/', destination: '/podcast/rob-arnott-research-affiliates/', permanent: true },
      { source: '/blog/john-davi/', destination: '/podcast/john-davi-astoria-advisors/', permanent: true },
      { source: '/blog/mike-loukas/', destination: '/podcast/mike-loukas-trueshares/', permanent: true },
      { source: '/blog/catherine-legraw/', destination: '/podcast/catherine-legraw-gmo/', permanent: true },
      { source: '/blog/kevin-carter/', destination: '/podcast/kevin-carter-emqq-global/', permanent: true },
      { source: '/blog/david-dziekanski-quantify-funds/', destination: '/podcast/david-dziekanski-quantify-funds/', permanent: true },
      { source: '/blog/ai-in-finance/', destination: '/podcast/ai-in-finance-ut-catt-2024-global-analytics-conference-kyle-wiggs-suhir-holla-ta/', permanent: true },
      { source: '/blog/al-chu/', destination: '/podcast/al-chu-american-beacon-glg-natural-resources-etf-mgnr/', permanent: true },
      { source: '/blog/raymond-holst/', destination: '/podcast/raymond-holst-practus/', permanent: true },
      { source: '/blog/garrett-stevens-rich-malinowski/', destination: '/podcast/garrett-stevens-rich-malinowski-exchange-traded-concepts/', permanent: true },
      { source: '/blog/brett-eichenberger/', destination: '/podcast/brett-eichenberger-cohen-co/', permanent: true },
      { source: '/blog/petra-bakosova/', destination: '/podcast/petra-bakosova-hull-tactical/', permanent: true },
      { source: '/blog/joe-benoit/', destination: '/podcast/joe-benoit-grimes-co/', permanent: true },
      { source: '/blog/david-allen/', destination: '/podcast/david-allen-octane-investments/', permanent: true },
      { source: '/blog/federico-brokate/', destination: '/podcast/federico-brokate-21shares/', permanent: true },
      { source: '/blog/nancy-davis/', destination: '/podcast/nancy-davis-quadratic-capital/', permanent: true },
      { source: '/blog/mike-venuto/', destination: '/podcast/mike-venuto-tidal-the-etf-masters/', permanent: true },
      { source: '/blog/sylvia-jablonski/', destination: '/podcast/sylvia-jablonski-defiance-etfs/', permanent: true },
      { source: '/blog/james-st-aubin/', destination: '/podcast/james-st-aubin-ocean-park-asset-management/', permanent: true },
      { source: '/blog/springer-harris/', destination: '/podcast/springer-harris-get-etf-d/', permanent: true },
      { source: '/blog/howard-chan/', destination: '/podcast/howard-chan-kurv-investment-management/', permanent: true },
      { source: '/blog/joanna-gallegos/', destination: '/podcast/joanna-gallegos-bondbloxx/', permanent: true },
      { source: '/blog/taylor-krystkowiak/', destination: '/podcast/taylor-krystkowiak-themesetfs/', permanent: true },
      { source: '/blog/will-rhind/', destination: '/podcast/will-rhind-graniteshares/', permanent: true },
      { source: '/blog/tim-kramer/', destination: '/podcast/tim-kramer-cnic-funds/', permanent: true },
      { source: '/blog/meb-faber/', destination: '/podcast/meb-faber-cambria-investments/', permanent: true },
      { source: '/blog/john-mchugh/', destination: '/podcast/john-mchugh-wealthtrust-asset-management/', permanent: true },
      { source: '/blog/andrew-skatoff/', destination: '/podcast/andrew-skatoff-bancreek/', permanent: true },
      { source: '/blog/danielle-gilbert/', destination: '/podcast/danielle-gilbert-panagram/', permanent: true },
      { source: '/blog/yang-tang/', destination: '/podcast/yang-tang-arch-indicies-vwi/', permanent: true },
      { source: '/blog/burke-ashenden/', destination: '/podcast/burke-ashenden-innovator-etfs/', permanent: true },
      { source: '/blog/jerry-parker/', destination: '/podcast/jerry-parker-chesapeake-capital/', permanent: true },
      { source: '/blog/bob-elliott/', destination: '/podcast/bob-elliott-hfnd/', permanent: true },
      { source: '/blog/andrew-beer/', destination: '/podcast/andrew-beer-dbmf/', permanent: true },
      { source: '/blog/matt-kaufman-2/', destination: '/podcast/matt-kaufman-calamos-cpsm/', permanent: true },
      { source: '/blog/jason-hsu/', destination: '/podcast/jason-hsu-rayliant/', permanent: true },
      { source: '/blog/greg-reid/', destination: '/podcast/greg-reid-westwood-mdst/', permanent: true },
      { source: '/blog/kim-mayer/', destination: '/podcast/kim-mayer-gmo/', permanent: true },
      { source: '/blog/simeon-hyman/', destination: '/podcast/simeon-hyman-proshares/', permanent: true },
      { source: '/blog/dodd-kittsley/', destination: '/podcast/dodd-kittsley-davis-funds/', permanent: true },
      { source: '/blog/sal-esposito/', destination: '/podcast/sal-esposito-zacks/', permanent: true },
      { source: '/blog/johan-grahn/', destination: '/podcast/johan-grahn-allianz/', permanent: true },
      { source: '/blog/weldon-rice/', destination: '/podcast/weldon-rice-qraft-ai/', permanent: true },
      { source: '/blog/david-lavalle/', destination: '/podcast/david-lavalle-grayscale-gbtc/', permanent: true },
      { source: '/blog/keri-riemer-hazel-doyle/', destination: '/podcast/keri-riemer-hazel-doyle-k-l-gates/', permanent: true },
      { source: '/blog/adam-curran/', destination: '/podcast/adam-curran-yall/', permanent: true },
      { source: '/blog/todd-rosenbluth/', destination: '/podcast/todd-rosenbluth-vettafi-exchange-etf/', permanent: true },
      { source: '/blog/matt-barry/', destination: '/podcast/matt-barry-touchstone-funds/', permanent: true },
      { source: '/blog/andrew-chanin/', destination: '/podcast/andrew-chanin-procuream-ufo-fixt/', permanent: true },
      { source: '/blog/yuri-khodjamirian/', destination: '/podcast/yuri-khodjamirian-tema-etfs-toll/', permanent: true },
      { source: '/blog/ragen-stienke/', destination: '/podcast/ragen-stienke-ballast-asset-management-mgmt/', permanent: true },
      { source: '/blog/steve-cook/', destination: '/podcast/steve-cook-harbor-funds/', permanent: true },
      { source: '/blog/katie-stockton/', destination: '/podcast/katie-stockton-fairlead-strategies-tack/', permanent: true },
      { source: '/blog/will-rhind-2/', destination: '/podcast/will-rhind-graniteshares-2023/', permanent: true },
      { source: '/blog/paul-weisbruch/', destination: '/podcast/paul-weisbruch-gts/', permanent: true },
      { source: '/blog/kyle-wiggs/', destination: '/podcast/kyle-wiggs-ux-wealth/', permanent: true },
      { source: '/blog/john-davi-frank-tedesco/', destination: '/podcast/john-davi-frank-tedesco-roe/', permanent: true },
      { source: '/blog/elysabeth-alfano/', destination: '/podcast/elysabeth-alfano-eatv/', permanent: true },
      { source: '/blog/ryan-pannell/', destination: '/podcast/ryan-pannell-dip/', permanent: true },
      { source: '/blog/alejandro-garza/', destination: '/podcast/alejandro-garza-aztd/', permanent: true },
      { source: '/blog/david-schulhof/', destination: '/podcast/david-schulhof-musq/', permanent: true },
      { source: '/blog/adam-eagleston/', destination: '/podcast/adam-eagleston-formidable-forh/', permanent: true },
      { source: '/blog/neil-azous/', destination: '/podcast/neil-azous-rareview-rsee/', permanent: true },
      { source: '/blog/john-forlines/', destination: '/podcast/john-forlines-donoghue-forlines-dfra/', permanent: true },
      { source: '/blog/john-davi-2/', destination: '/podcast/john-davi-astoria-advisors-ppi/', permanent: true },
      { source: '/blog/michael-gayed/', destination: '/podcast/michael-gayed-roro-jojo/', permanent: true },
      { source: '/blog/michael-venuto/', destination: '/podcast/michael-venuto-tidal-blok/', permanent: true },
      { source: '/blog/dan-cupkovic/', destination: '/podcast/dan-cupkovic-black-swan/', permanent: true },
      { source: '/blog/david-cohen/', destination: '/podcast/david-cohen-handls-indexes/', permanent: true },
      { source: '/blog/dave-mazza/', destination: '/podcast/dave-mazza-chat-etf/', permanent: true },
      { source: '/blog/garrett-stevens/', destination: '/podcast/garrett-stevens-exchange-traded-concepts/', permanent: true },
      { source: '/blog/daniel-snover/', destination: '/podcast/daniel-snover-arp-etf/', permanent: true },
      { source: '/blog/patricia-lizarraga/', destination: '/podcast/patricia-lizarraga-wceo-etf/', permanent: true },
      { source: '/blog/tommy-mancuso/', destination: '/podcast/tommy-mancuso-the-bad-etf/', permanent: true },
      { source: '/blog/introduction-to-behind-the-ticker/', destination: '/podcast/introduction-to-behind-the-ticker/', permanent: true },
    ];
  },
};

export default nextConfig;
