// THOR Dollar ALT model performance data
// GENERATED by ~/clawd/scripts/update-model-performance.mjs — do not hand-edit.
// Generated: 2026-06-10T15:13:22.555Z
// Source of truth: data/performance/dollar-alt.csv
// All returns are monthly percentages. NET returns used throughout.
// Coverage: January 2018 through February 2026 (complete months only).

export interface MonthlyReturn {
  date: string; // YYYY-MM-DD (calendar month end)
  thorNet: number; // monthly return in %
  benchmark: number; // monthly return in %
}

export const monthlyReturns: MonthlyReturn[] = [
  { date: "2018-01-31", thorNet: 2.823743, benchmark: 2.56885 },
  { date: "2018-02-28", thorNet: -3.439923, benchmark: -2.71448 },
  { date: "2018-03-31", thorNet: 0.017881, benchmark: -0.909489 },
  { date: "2018-04-30", thorNet: -2.857301, benchmark: -0.653408 },
  { date: "2018-05-31", thorNet: -0.928444, benchmark: -0.344504 },
  { date: "2018-06-30", thorNet: -1.28423, benchmark: -3.299798 },
  { date: "2018-07-31", thorNet: 0.039344, benchmark: -2.599953 },
  { date: "2018-08-31", thorNet: 0.360559, benchmark: -2.986315 },
  { date: "2018-09-30", thorNet: -0.172888, benchmark: 0.964724 },
  { date: "2018-10-31", thorNet: 0.040221, benchmark: 0.679593 },
  { date: "2018-11-30", thorNet: 0.348625, benchmark: 0.693636 },
  { date: "2018-12-31", thorNet: 1.209586, benchmark: 6.115593 },
  { date: "2019-01-31", thorNet: 1.815745, benchmark: 3.514885 },
  { date: "2019-02-28", thorNet: -1.244415, benchmark: 0.841229 },
  { date: "2019-03-31", thorNet: -2.200815, benchmark: -3.412729 },
  { date: "2019-04-30", thorNet: -0.865631, benchmark: -0.282674 },
  { date: "2019-05-31", thorNet: 0.583755, benchmark: -0.788037 },
  { date: "2019-06-30", thorNet: 4.695758, benchmark: 8.056242 },
  { date: "2019-07-31", thorNet: 2.456232, benchmark: 1.593846 },
  { date: "2019-08-31", thorNet: 9.908924, benchmark: 8.270672 },
  { date: "2019-09-30", thorNet: -2.786767, benchmark: -3.071574 },
  { date: "2019-10-31", thorNet: 1.678043, benchmark: 4.19811 },
  { date: "2019-11-30", thorNet: -1.980169, benchmark: -3.200179 },
  { date: "2019-12-31", thorNet: 2.246031, benchmark: 4.361873 },
  { date: "2020-01-31", thorNet: 3.036886, benchmark: 5.353392 },
  { date: "2020-02-29", thorNet: -4.46688, benchmark: -0.614359 },
  { date: "2020-03-31", thorNet: 2.208501, benchmark: -6.119716 },
  { date: "2020-04-30", thorNet: 2.184242, benchmark: 3.608524 },
  { date: "2020-05-31", thorNet: 9.101112, benchmark: 5.410623 },
  { date: "2020-06-30", thorNet: 2.447605, benchmark: 1.841031 },
  { date: "2020-07-31", thorNet: 20.584482, benchmark: 15.527385 },
  { date: "2020-08-31", thorNet: 1.025297, benchmark: 4.943003 },
  { date: "2020-09-30", thorNet: -1.721853, benchmark: -7.218313 },
  { date: "2020-10-31", thorNet: -2.546213, benchmark: -0.69179 },
  { date: "2020-11-30", thorNet: 0.049423, benchmark: -2.722097 },
  { date: "2020-12-31", thorNet: 3.792548, benchmark: 9.011769 },
  { date: "2021-01-31", thorNet: 0.851967, benchmark: -2.516386 },
  { date: "2021-02-28", thorNet: -1.101295, benchmark: -2.871653 },
  { date: "2021-03-31", thorNet: -0.202186, benchmark: -1.088682 },
  { date: "2021-04-30", thorNet: -0.085202, benchmark: 5.287583 },
  { date: "2021-05-31", thorNet: 4.183282, benchmark: 5.442247 },
  { date: "2021-06-30", thorNet: -6.76564, benchmark: -6.249991 },
  { date: "2021-07-31", thorNet: -0.017076, benchmark: -0.197004 },
  { date: "2021-08-31", thorNet: -0.020632, benchmark: -3.023085 },
  { date: "2021-09-30", thorNet: -1.920467, benchmark: -7.380811 },
  { date: "2021-10-31", thorNet: 0.08051, benchmark: 3.654883 },
  { date: "2021-11-30", thorNet: -2.224383, benchmark: -3.648747 },
  { date: "2021-12-31", thorNet: 2.776734, benchmark: 3.593039 },
  { date: "2022-01-31", thorNet: -2.267498, benchmark: 1.327393 },
  { date: "2022-02-28", thorNet: 6.951169, benchmark: 6.636126 },
  { date: "2022-03-31", thorNet: 1.184719, benchmark: -0.594905 },
  { date: "2022-04-30", thorNet: -4.289374, benchmark: -3.37219 },
  { date: "2022-05-31", thorNet: -4.094335, benchmark: -4.890142 },
  { date: "2022-06-30", thorNet: -3.139333, benchmark: -3.363521 },
  { date: "2022-07-31", thorNet: -4.005859, benchmark: -0.11718 },
  { date: "2022-08-31", thorNet: -0.01694, benchmark: -5.021729 },
  { date: "2022-09-30", thorNet: -0.016393, benchmark: 0.222358 },
  { date: "2022-10-31", thorNet: -0.797719, benchmark: -2.773318 },
  { date: "2022-11-30", thorNet: 6.157081, benchmark: 9.660232 },
  { date: "2022-12-31", thorNet: 4.773044, benchmark: 3.156064 },
  { date: "2023-01-31", thorNet: 2.940511, benchmark: 1.927598 },
  { date: "2023-02-28", thorNet: -6.745461, benchmark: -7.993395 },
  { date: "2023-03-31", thorNet: 4.641814, benchmark: 8.99855 },
  { date: "2023-04-30", thorNet: 0.506916, benchmark: 2.192732 },
  { date: "2023-05-31", thorNet: -0.834036, benchmark: -3.615491 },
  { date: "2023-06-30", thorNet: -1.361727, benchmark: -3.428312 },
  { date: "2023-07-31", thorNet: 1.356931, benchmark: 4.207013 },
  { date: "2023-08-31", thorNet: -0.790895, benchmark: -1.437899 },
  { date: "2023-09-30", thorNet: -2.885343, benchmark: -5.56078 },
  { date: "2023-10-31", thorNet: 4.339279, benchmark: 4.628648 },
  { date: "2023-11-30", thorNet: 1.522552, benchmark: 3.56614 },
  { date: "2023-12-31", thorNet: 0.770141, benchmark: -0.186414 },
  { date: "2024-01-31", thorNet: -0.894709, benchmark: -2.933425 },
  { date: "2024-02-29", thorNet: 0.264192, benchmark: -0.282956 },
  { date: "2024-03-31", thorNet: 5.310798, benchmark: 8.399562 },
  { date: "2024-04-30", thorNet: 1.879021, benchmark: 3.465953 },
  { date: "2024-05-31", thorNet: 1.020557, benchmark: 5.242363 },
  { date: "2024-06-30", thorNet: -0.103216, benchmark: -0.971244 },
  { date: "2024-07-31", thorNet: 3.441219, benchmark: 2.505366 },
  { date: "2024-08-31", thorNet: 1.355836, benchmark: 1.354668 },
  { date: "2024-09-30", thorNet: 3.346332, benchmark: 5.888403 },
  { date: "2024-10-31", thorNet: 2.871384, benchmark: 4.6915 },
  { date: "2024-11-30", thorNet: -2.14403, benchmark: -4.514978 },
  { date: "2024-12-31", thorNet: -0.966615, benchmark: -3.046358 },
  { date: "2025-01-31", thorNet: 4.536249, benchmark: 7.459026 },
  { date: "2025-02-28", thorNet: 1.23306, benchmark: 0.415283 },
  { date: "2025-03-31", thorNet: 6.493857, benchmark: 9.275838 },
  { date: "2025-04-30", thorNet: 2.880978, benchmark: 2.023635 },
  { date: "2025-05-31", thorNet: -0.051129, benchmark: 0.83278 },
  { date: "2025-06-30", thorNet: 0.230682, benchmark: 3.723984 },
  { date: "2025-07-31", thorNet: -0.391399, benchmark: 0.267853 },
  { date: "2025-08-31", thorNet: 3.020802, benchmark: 5.378292 },
  { date: "2025-09-30", thorNet: 7.280755, benchmark: 13.345217 },
  { date: "2025-10-31", thorNet: 2.283229, benchmark: 4.019354 },
  { date: "2025-11-30", thorNet: 3.496048, benchmark: 8.361419 },
  { date: "2025-12-31", thorNet: 1.430542, benchmark: 10.247223 },
  { date: "2026-01-31", thorNet: 8.214618, benchmark: 13.735326 },
  { date: "2026-02-28", thorNet: 6.07, benchmark: 9.6989 },
];

// ─── Helper functions ───

function compoundReturns(returns: number[]): number {
  let cumulative = 1;
  for (const r of returns) {
    cumulative *= 1 + r / 100;
  }
  return (cumulative - 1) * 100;
}

function annualizeReturn(totalReturnPct: number, months: number): number {
  const totalFactor = 1 + totalReturnPct / 100;
  const annualized = Math.pow(totalFactor, 12 / months) - 1;
  return annualized * 100;
}

// ─── Standard Period Returns ───
// All periods are derived from the END of the series (the as-of month):
// MTD = the as-of month; QTD/YTD = calendar quarter/year to the as-of month;
// trailing periods use exact 12/36/60/120-month windows.

function calcStandardPeriods() {
  const data = monthlyReturns;
  const lastDate = data[data.length - 1].date;
  const year = lastDate.slice(0, 4);
  const month = Number(lastDate.slice(5, 7));
  const quarterStartMonth = Math.floor((month - 1) / 3) * 3 + 1;
  const quarterStart = `${year}-${String(quarterStartMonth).padStart(2, "0")}-01`;
  const yearStart = `${year}-01-01`;

  const inPeriod = (start: string) => data.filter((d) => d.date >= start);

  const mtd = {
    thor: data[data.length - 1].thorNet,
    bench: data[data.length - 1].benchmark,
  };
  const qtd = {
    thor: compoundReturns(inPeriod(quarterStart).map((d) => d.thorNet)),
    bench: compoundReturns(inPeriod(quarterStart).map((d) => d.benchmark)),
  };
  const ytd = {
    thor: compoundReturns(inPeriod(yearStart).map((d) => d.thorNet)),
    bench: compoundReturns(inPeriod(yearStart).map((d) => d.benchmark)),
  };

  const oneYear = {
    thor: compoundReturns(data.slice(-12).map((d) => d.thorNet)),
    bench: compoundReturns(data.slice(-12).map((d) => d.benchmark)),
  };

  const threeYear = {
    thor: annualizeReturn(compoundReturns(data.slice(-36).map((d) => d.thorNet)), 36),
    bench: annualizeReturn(compoundReturns(data.slice(-36).map((d) => d.benchmark)), 36),
  };

  const fiveYear = {
    thor: annualizeReturn(compoundReturns(data.slice(-60).map((d) => d.thorNet)), 60),
    bench: annualizeReturn(compoundReturns(data.slice(-60).map((d) => d.benchmark)), 60),
  };

  const sinceInception = {
    thor: annualizeReturn(compoundReturns(data.map((d) => d.thorNet)), data.length),
    bench: annualizeReturn(compoundReturns(data.map((d) => d.benchmark)), data.length),
  };

  return {
    mtd,
    qtd,
    ytd,
    oneYear,
    threeYear,
    fiveYear,
    sinceInception,
  };
}

// ─── Calendar Year Returns ───

function calcCalendarYears() {
  const years = Array.from(new Set(monthlyReturns.map((d) => d.date.slice(0, 4)))).sort();
  return years.map((yearStr) => {
    const yearData = monthlyReturns.filter((d) => d.date.startsWith(`${yearStr}-`));
    return {
      year: Number(yearStr),
      thor: compoundReturns(yearData.map((d) => d.thorNet)),
      bench: compoundReturns(yearData.map((d) => d.benchmark)),
    };
  });
}

// ─── Growth of $10,000 ───

function calcGrowthOf10K() {
  let thorValue = 10000;
  let benchValue = 10000;

  for (const m of monthlyReturns) {
    thorValue *= 1 + m.thorNet / 100;
    benchValue *= 1 + m.benchmark / 100;
  }

  return {
    thor: Math.round(thorValue),
    bench: Math.round(benchValue),
  };
}

// ─── Risk Statistics ───

function calcRiskStats() {
  const thorReturns = monthlyReturns.map((d) => d.thorNet);
  const benchReturns = monthlyReturns.map((d) => d.benchmark);
  const n = thorReturns.length;

  const thorCumulative = compoundReturns(thorReturns);
  const benchCumulative = compoundReturns(benchReturns);
  const thorAnnReturn = annualizeReturn(thorCumulative, n);
  const benchAnnReturn = annualizeReturn(benchCumulative, n);

  const thorMean = thorReturns.reduce((a, b) => a + b, 0) / n;
  const benchMean = benchReturns.reduce((a, b) => a + b, 0) / n;
  const thorMonthlyStd = Math.sqrt(thorReturns.reduce((sum, r) => sum + (r - thorMean) ** 2, 0) / (n - 1));
  const benchMonthlyStd = Math.sqrt(benchReturns.reduce((sum, r) => sum + (r - benchMean) ** 2, 0) / (n - 1));
  const thorAnnStd = thorMonthlyStd * Math.sqrt(12);
  const benchAnnStd = benchMonthlyStd * Math.sqrt(12);

  // Sharpe Ratio (risk-free = 2% long-term average)
  const riskFree = 2.0;
  const thorSharpe = (thorAnnReturn - riskFree) / thorAnnStd;
  const benchSharpe = (benchAnnReturn - riskFree) / benchAnnStd;

  function maxDrawdown(returns: number[]): number {
    let peak = 1;
    let cumulative = 1;
    let maxDD = 0;
    for (const r of returns) {
      cumulative *= 1 + r / 100;
      if (cumulative > peak) peak = cumulative;
      const dd = (cumulative - peak) / peak;
      if (dd < maxDD) maxDD = dd;
    }
    return maxDD * 100;
  }

  const thorMaxDD = maxDrawdown(thorReturns);
  const benchMaxDD = maxDrawdown(benchReturns);

  const thorBest = Math.max(...thorReturns);
  const thorWorst = Math.min(...thorReturns);
  const benchBest = Math.max(...benchReturns);
  const benchWorst = Math.min(...benchReturns);

  const thorPositive = (thorReturns.filter((r) => r > 0).length / n) * 100;
  const benchPositive = (benchReturns.filter((r) => r > 0).length / n) * 100;

  return {
    annualizedReturn: { thor: thorAnnReturn, bench: benchAnnReturn },
    annualizedStdDev: { thor: thorAnnStd, bench: benchAnnStd },
    sharpeRatio: { thor: thorSharpe, bench: benchSharpe },
    maxDrawdown: { thor: thorMaxDD, bench: benchMaxDD },
    bestMonth: { thor: thorBest, bench: benchBest },
    worstMonth: { thor: thorWorst, bench: benchWorst },
    positiveMonths: { thor: thorPositive, bench: benchPositive },
  };
}

// ─── Export all computed data ───

export const standardPeriods = calcStandardPeriods();
export const calendarYears = calcCalendarYears();
export const growthOf10K = calcGrowthOf10K();
export const riskStats = calcRiskStats();
