// THOR International model performance data
// GENERATED by ~/clawd/scripts/update-model-performance.mjs — do not hand-edit.
// Generated: 2026-06-10T15:13:22.555Z
// Source of truth: data/performance/international.csv
// All returns are monthly percentages. NET returns used throughout.
// Coverage: January 2017 through May 2026 (complete months only).

export interface MonthlyReturn {
  date: string; // YYYY-MM-DD (calendar month end)
  thorNet: number; // monthly return in %
  benchmark: number; // monthly return in %
}

export const monthlyReturns: MonthlyReturn[] = [
  { date: "2017-01-31", thorNet: 2.826414, benchmark: 2.999989 },
  { date: "2017-02-28", thorNet: 0.978624, benchmark: 2.689786 },
  { date: "2017-03-31", thorNet: 3.708518, benchmark: 1.475908 },
  { date: "2017-04-30", thorNet: 1.739151, benchmark: 1.625265 },
  { date: "2017-05-31", thorNet: 3.835562, benchmark: 1.946296 },
  { date: "2017-06-30", thorNet: 0.517681, benchmark: 0.625501 },
  { date: "2017-07-31", thorNet: 3.987478, benchmark: 2.650681 },
  { date: "2017-08-31", thorNet: 0.310789, benchmark: 0.41834 },
  { date: "2017-09-30", thorNet: 2.308189, benchmark: 2.106617 },
  { date: "2017-10-31", thorNet: 2.735923, benchmark: 2.106894 },
  { date: "2017-11-30", thorNet: 0.711608, benchmark: 1.897244 },
  { date: "2017-12-31", thorNet: 1.596877, benchmark: 1.596217 },
  { date: "2018-01-31", thorNet: 5.955549, benchmark: 5.480725 },
  { date: "2018-02-28", thorNet: -5.307161, benchmark: -4.442741 },
  { date: "2018-03-31", thorNet: -0.01694, benchmark: -1.286695 },
  { date: "2018-04-30", thorNet: -0.016393, benchmark: 0.421029 },
  { date: "2018-05-31", thorNet: -0.01694, benchmark: 0.568033 },
  { date: "2018-06-30", thorNet: -0.016393, benchmark: -0.599601 },
  { date: "2018-07-31", thorNet: -0.01694, benchmark: 2.875808 },
  { date: "2018-08-31", thorNet: -0.01694, benchmark: 0.86116 },
  { date: "2018-09-30", thorNet: -0.016393, benchmark: 0.079425 },
  { date: "2018-10-31", thorNet: -0.01694, benchmark: -7.820124 },
  { date: "2018-11-30", thorNet: 0.978071, benchmark: 1.731033 },
  { date: "2018-12-31", thorNet: 0.145294, benchmark: -7.223249 },
  { date: "2019-01-31", thorNet: 1.188227, benchmark: 7.989624 },
  { date: "2019-02-28", thorNet: 1.773043, benchmark: 2.815085 },
  { date: "2019-03-31", thorNet: 1.127512, benchmark: 1.064793 },
  { date: "2019-04-30", thorNet: 2.83667, benchmark: 3.471356 },
  { date: "2019-05-31", thorNet: -6.490434, benchmark: -5.97013 },
  { date: "2019-06-30", thorNet: 5.686402, benchmark: 6.368651 },
  { date: "2019-07-31", thorNet: -2.82831, benchmark: -0.000005 },
  { date: "2019-08-31", thorNet: -2.982455, benchmark: -2.102175 },
  { date: "2019-09-30", thorNet: 2.380965, benchmark: 2.276085 },
  { date: "2019-10-31", thorNet: 3.177384, benchmark: 2.793373 },
  { date: "2019-11-30", thorNet: 1.214397, benchmark: 2.561452 },
  { date: "2019-12-31", thorNet: 3.808281, benchmark: 3.451522 },
  { date: "2020-01-31", thorNet: -3.466563, benchmark: -1.555723 },
  { date: "2020-02-29", thorNet: -6.372483, benchmark: -7.224377 },
  { date: "2020-03-31", thorNet: 1.178076, benchmark: -14.757081 },
  { date: "2020-04-30", thorNet: 8.254174, benchmark: 10.366233 },
  { date: "2020-05-31", thorNet: 4.578984, benchmark: 5.208489 },
  { date: "2020-06-30", thorNet: 4.636045, benchmark: 3.066897 },
  { date: "2020-07-31", thorNet: 4.647536, benchmark: 5.294133 },
  { date: "2020-08-31", thorNet: 5.465118, benchmark: 6.005583 },
  { date: "2020-09-30", thorNet: -1.693173, benchmark: -2.925021 },
  { date: "2020-10-31", thorNet: 0.364912, benchmark: -2.04615 },
  { date: "2020-11-30", thorNet: 8.794641, benchmark: 12.368668 },
  { date: "2020-12-31", thorNet: 5.675564, benchmark: 4.936559 },
  { date: "2021-01-31", thorNet: -0.230915, benchmark: -0.226818 },
  { date: "2021-02-28", thorNet: 3.215187, benchmark: 2.674031 },
  { date: "2021-03-31", thorNet: 2.387412, benchmark: 2.849832 },
  { date: "2021-04-30", thorNet: 2.334682, benchmark: 4.131985 },
  { date: "2021-05-31", thorNet: 4.022015, benchmark: 1.579341 },
  { date: "2021-06-30", thorNet: -1.363365, benchmark: 1.175098 },
  { date: "2021-07-31", thorNet: -0.327675, benchmark: 0.617715 },
  { date: "2021-08-31", thorNet: 1.746896, benchmark: 2.263765 },
  { date: "2021-09-30", thorNet: -1.745618, benchmark: -4.100838 },
  { date: "2021-10-31", thorNet: 3.514253, benchmark: 5.145817 },
  { date: "2021-11-30", thorNet: -2.999252, benchmark: -2.615117 },
  { date: "2021-12-31", thorNet: 2.827143, benchmark: 3.813105 },
  { date: "2022-01-31", thorNet: -1.417841, benchmark: -4.579715 },
  { date: "2022-02-28", thorNet: -0.015301, benchmark: -2.770467 },
  { date: "2022-03-31", thorNet: -0.621791, benchmark: 1.886319 },
  { date: "2022-04-30", thorNet: -4.836813, benchmark: -8.095589 },
  { date: "2022-05-31", thorNet: 0.296549, benchmark: 0.494168 },
  { date: "2022-06-30", thorNet: -3.004436, benchmark: -8.135407 },
  { date: "2022-07-31", thorNet: -1.810522, benchmark: 6.983839 },
  { date: "2022-08-31", thorNet: -4.145722, benchmark: -4.052585 },
  { date: "2022-09-30", thorNet: -6.357285, benchmark: -9.531962 },
  { date: "2022-10-31", thorNet: 8.288131, benchmark: 6.376779 },
  { date: "2022-11-30", thorNet: 12.443557, benchmark: 8.282675 },
  { date: "2022-12-31", thorNet: -2.861684, benchmark: -4.432968 },
  { date: "2023-01-31", thorNet: 9.184158, benchmark: 7.645897 },
  { date: "2023-02-28", thorNet: -4.149524, benchmark: -3.179557 },
  { date: "2023-03-31", thorNet: 2.321698, benchmark: 2.846808 },
  { date: "2023-04-30", thorNet: 2.109913, benchmark: 1.422503 },
  { date: "2023-05-31", thorNet: -2.872314, benchmark: -1.209864 },
  { date: "2023-06-30", thorNet: 4.623438, benchmark: 5.815432 },
  { date: "2023-07-31", thorNet: 3.24547, benchmark: 3.722371 },
  { date: "2023-08-31", thorNet: -5.173335, benchmark: -2.843231 },
  { date: "2023-09-30", thorNet: -1.332346, benchmark: -4.254806 },
  { date: "2023-10-31", thorNet: 0.380791, benchmark: -2.919094 },
  { date: "2023-11-30", thorNet: 0.697106, benchmark: 9.009498 },
  { date: "2023-12-31", thorNet: 2.91747, benchmark: 5.154058 },
  { date: "2024-01-31", thorNet: -2.722464, benchmark: -0.000007 },
  { date: "2024-02-29", thorNet: 3.444955, benchmark: 4.490672 },
  { date: "2024-03-31", thorNet: 2.931353, benchmark: 3.191079 },
  { date: "2024-04-30", thorNet: -1.562637, benchmark: -3.583723 },
  { date: "2024-05-31", thorNet: 3.362713, benchmark: 4.599211 },
  { date: "2024-06-30", thorNet: -1.318931, benchmark: 1.587341 },
  { date: "2024-07-31", thorNet: 3.537042, benchmark: 1.979928 },
  { date: "2024-08-31", thorNet: 0.228374, benchmark: 2.33327 },
  { date: "2024-09-30", thorNet: 0.814363, benchmark: 2.198218 },
  { date: "2024-10-31", thorNet: -2.531797, benchmark: -2.180449 },
  { date: "2024-11-30", thorNet: 0.528912, benchmark: 4.142106 },
  { date: "2024-12-31", thorNet: -0.994285, benchmark: -2.94183 },
  { date: "2025-01-31", thorNet: 0.925252, benchmark: 3.055828 },
  { date: "2025-02-28", thorNet: 0.120125, benchmark: -0.412979 },
  { date: "2025-03-31", thorNet: -0.437085, benchmark: -3.516821 },
  { date: "2025-04-30", thorNet: 7.617474, benchmark: 0.560597 },
  { date: "2025-05-31", thorNet: 5.407267, benchmark: 5.806161 },
  { date: "2025-06-30", thorNet: 4.712305, benchmark: 4.675079 },
  { date: "2025-07-31", thorNet: -0.469452, benchmark: 1.097091 },
  { date: "2025-08-31", thorNet: 2.925271, benchmark: 2.955434 },
  { date: "2025-09-30", thorNet: 2.953421, benchmark: 3.370911 },
  { date: "2025-10-31", thorNet: 4.073577, benchmark: 2.024662 },
  { date: "2025-11-30", thorNet: -0.521561, benchmark: 0.213355 },
  { date: "2025-12-31", thorNet: 3.688455, benchmark: 0.915351 },
  { date: "2026-01-31", thorNet: 7.712943, benchmark: 3.112162 },
  { date: "2026-02-28", thorNet: 8.69, benchmark: 1.6432 },
  { date: "2026-03-31", thorNet: -10.643171, benchmark: -6.21964 },
  { date: "2026-04-30", thorNet: 0.248076, benchmark: 9.311733 },
  { date: "2026-05-31", thorNet: 0.276572, benchmark: 4.576718 },
];

// ─── Helper functions ───

function compoundReturns(returns: number[]): number {
  let cumulative = 1;
  for (const r of returns) {
    cumulative *= 1 + r / 100;
  }
  return (cumulative - 1) * 100;
}

function annualizeReturn(totalReturnPct: number, months: number): number {
  const totalFactor = 1 + totalReturnPct / 100;
  const annualized = Math.pow(totalFactor, 12 / months) - 1;
  return annualized * 100;
}

// ─── Standard Period Returns ───
// All periods are derived from the END of the series (the as-of month):
// MTD = the as-of month; QTD/YTD = calendar quarter/year to the as-of month;
// trailing periods use exact 12/36/60/120-month windows.

function calcStandardPeriods() {
  const data = monthlyReturns;
  const lastDate = data[data.length - 1].date;
  const year = lastDate.slice(0, 4);
  const month = Number(lastDate.slice(5, 7));
  const quarterStartMonth = Math.floor((month - 1) / 3) * 3 + 1;
  const quarterStart = `${year}-${String(quarterStartMonth).padStart(2, "0")}-01`;
  const yearStart = `${year}-01-01`;

  const inPeriod = (start: string) => data.filter((d) => d.date >= start);

  const mtd = {
    thor: data[data.length - 1].thorNet,
    bench: data[data.length - 1].benchmark,
  };
  const qtd = {
    thor: compoundReturns(inPeriod(quarterStart).map((d) => d.thorNet)),
    bench: compoundReturns(inPeriod(quarterStart).map((d) => d.benchmark)),
  };
  const ytd = {
    thor: compoundReturns(inPeriod(yearStart).map((d) => d.thorNet)),
    bench: compoundReturns(inPeriod(yearStart).map((d) => d.benchmark)),
  };

  const oneYear = {
    thor: compoundReturns(data.slice(-12).map((d) => d.thorNet)),
    bench: compoundReturns(data.slice(-12).map((d) => d.benchmark)),
  };

  const threeYear = {
    thor: annualizeReturn(compoundReturns(data.slice(-36).map((d) => d.thorNet)), 36),
    bench: annualizeReturn(compoundReturns(data.slice(-36).map((d) => d.benchmark)), 36),
  };

  const fiveYear = {
    thor: annualizeReturn(compoundReturns(data.slice(-60).map((d) => d.thorNet)), 60),
    bench: annualizeReturn(compoundReturns(data.slice(-60).map((d) => d.benchmark)), 60),
  };

  const sinceInception = {
    thor: annualizeReturn(compoundReturns(data.map((d) => d.thorNet)), data.length),
    bench: annualizeReturn(compoundReturns(data.map((d) => d.benchmark)), data.length),
  };

  return {
    mtd,
    qtd,
    ytd,
    oneYear,
    threeYear,
    fiveYear,
    sinceInception,
  };
}

// ─── Calendar Year Returns ───

function calcCalendarYears() {
  const years = Array.from(new Set(monthlyReturns.map((d) => d.date.slice(0, 4)))).sort();
  return years.map((yearStr) => {
    const yearData = monthlyReturns.filter((d) => d.date.startsWith(`${yearStr}-`));
    return {
      year: Number(yearStr),
      thor: compoundReturns(yearData.map((d) => d.thorNet)),
      bench: compoundReturns(yearData.map((d) => d.benchmark)),
    };
  });
}

// ─── Growth of $10,000 ───

function calcGrowthOf10K() {
  let thorValue = 10000;
  let benchValue = 10000;

  for (const m of monthlyReturns) {
    thorValue *= 1 + m.thorNet / 100;
    benchValue *= 1 + m.benchmark / 100;
  }

  return {
    thor: Math.round(thorValue),
    bench: Math.round(benchValue),
  };
}

// ─── Risk Statistics ───

function calcRiskStats() {
  const thorReturns = monthlyReturns.map((d) => d.thorNet);
  const benchReturns = monthlyReturns.map((d) => d.benchmark);
  const n = thorReturns.length;

  const thorCumulative = compoundReturns(thorReturns);
  const benchCumulative = compoundReturns(benchReturns);
  const thorAnnReturn = annualizeReturn(thorCumulative, n);
  const benchAnnReturn = annualizeReturn(benchCumulative, n);

  const thorMean = thorReturns.reduce((a, b) => a + b, 0) / n;
  const benchMean = benchReturns.reduce((a, b) => a + b, 0) / n;
  const thorMonthlyStd = Math.sqrt(thorReturns.reduce((sum, r) => sum + (r - thorMean) ** 2, 0) / (n - 1));
  const benchMonthlyStd = Math.sqrt(benchReturns.reduce((sum, r) => sum + (r - benchMean) ** 2, 0) / (n - 1));
  const thorAnnStd = thorMonthlyStd * Math.sqrt(12);
  const benchAnnStd = benchMonthlyStd * Math.sqrt(12);

  // Sharpe Ratio (risk-free = 2% long-term average)
  const riskFree = 2.0;
  const thorSharpe = (thorAnnReturn - riskFree) / thorAnnStd;
  const benchSharpe = (benchAnnReturn - riskFree) / benchAnnStd;

  function maxDrawdown(returns: number[]): number {
    let peak = 1;
    let cumulative = 1;
    let maxDD = 0;
    for (const r of returns) {
      cumulative *= 1 + r / 100;
      if (cumulative > peak) peak = cumulative;
      const dd = (cumulative - peak) / peak;
      if (dd < maxDD) maxDD = dd;
    }
    return maxDD * 100;
  }

  const thorMaxDD = maxDrawdown(thorReturns);
  const benchMaxDD = maxDrawdown(benchReturns);

  const thorBest = Math.max(...thorReturns);
  const thorWorst = Math.min(...thorReturns);
  const benchBest = Math.max(...benchReturns);
  const benchWorst = Math.min(...benchReturns);

  const thorPositive = (thorReturns.filter((r) => r > 0).length / n) * 100;
  const benchPositive = (benchReturns.filter((r) => r > 0).length / n) * 100;

  return {
    annualizedReturn: { thor: thorAnnReturn, bench: benchAnnReturn },
    annualizedStdDev: { thor: thorAnnStd, bench: benchAnnStd },
    sharpeRatio: { thor: thorSharpe, bench: benchSharpe },
    maxDrawdown: { thor: thorMaxDD, bench: benchMaxDD },
    bestMonth: { thor: thorBest, bench: benchBest },
    worstMonth: { thor: thorWorst, bench: benchWorst },
    positiveMonths: { thor: thorPositive, bench: benchPositive },
  };
}

// ─── Export all computed data ───

export const standardPeriods = calcStandardPeriods();
export const calendarYears = calcCalendarYears();
export const growthOf10K = calcGrowthOf10K();
export const riskStats = calcRiskStats();
