// THOR Levered Index model performance data
// GENERATED by ~/clawd/scripts/update-model-performance.mjs — do not hand-edit.
// Generated: 2026-06-10T15:13:22.555Z
// Source of truth: data/performance/levered-index.csv
// All returns are monthly percentages. NET returns used throughout.
// Coverage: December 2020 through February 2026 (complete months only).

export interface MonthlyReturn {
  date: string; // YYYY-MM-DD (calendar month end)
  thorNet: number; // monthly return in %
  benchmark: number; // monthly return in %
}

export const monthlyReturns: MonthlyReturn[] = [
  { date: "2020-12-31", thorNet: 0.690384, benchmark: 0.508082 },
  { date: "2021-01-31", thorNet: -0.650521, benchmark: -1.019052 },
  { date: "2021-02-28", thorNet: 2.13321, benchmark: 2.780556 },
  { date: "2021-03-31", thorNet: 3.857959, benchmark: 4.540527 },
  { date: "2021-04-30", thorNet: 7.398864, benchmark: 5.291029 },
  { date: "2021-05-31", thorNet: -1.186996, benchmark: 0.656623 },
  { date: "2021-06-30", thorNet: 2.495196, benchmark: 2.247293 },
  { date: "2021-07-31", thorNet: 1.329196, benchmark: 2.441267 },
  { date: "2021-08-31", thorNet: 3.605307, benchmark: 2.975983 },
  { date: "2021-09-30", thorNet: -5.739224, benchmark: -4.657525 },
  { date: "2021-10-31", thorNet: 7.90542, benchmark: 7.016357 },
  { date: "2021-11-30", thorNet: -0.541192, benchmark: -0.803504 },
  { date: "2021-12-31", thorNet: 1.637641, benchmark: 4.629499 },
  { date: "2022-01-31", thorNet: -4.345626, benchmark: -5.274114 },
  { date: "2022-02-28", thorNet: -1.82131, benchmark: -2.951687 },
  { date: "2022-03-31", thorNet: 1.701137, benchmark: 3.755553 },
  { date: "2022-04-30", thorNet: -7.584292, benchmark: -8.776879 },
  { date: "2022-05-31", thorNet: 0.509867, benchmark: 0.22574 },
  { date: "2022-06-30", thorNet: -4.101936, benchmark: -8.246916 },
  { date: "2022-07-31", thorNet: 6.822251, benchmark: 9.208742 },
  { date: "2022-08-31", thorNet: -3.275879, benchmark: -4.080216 },
  { date: "2022-09-30", thorNet: -6.478289, benchmark: -9.241646 },
  { date: "2022-10-31", thorNet: 6.350724, benchmark: 8.12757 },
  { date: "2022-11-30", thorNet: 6.064724, benchmark: 5.559141 },
  { date: "2022-12-31", thorNet: -6.452183, benchmark: -5.75758 },
  { date: "2023-01-31", thorNet: 7.775457, benchmark: 6.288742 },
  { date: "2023-02-28", thorNet: -1.99144, benchmark: -2.514273 },
  { date: "2023-03-31", thorNet: 5.157288, benchmark: 3.712488 },
  { date: "2023-04-30", thorNet: 1.978663, benchmark: 1.597486 },
  { date: "2023-05-31", thorNet: 0.374425, benchmark: 0.461635 },
  { date: "2023-06-30", thorNet: 8.980346, benchmark: 6.481419 },
  { date: "2023-07-31", thorNet: 4.453081, benchmark: 3.273281 },
  { date: "2023-08-31", thorNet: -2.298237, benchmark: -1.625209 },
  { date: "2023-09-30", thorNet: -2.897834, benchmark: -4.739335 },
  { date: "2023-10-31", thorNet: -3.69968, benchmark: -2.170853 },
  { date: "2023-11-30", thorNet: 10.36843, benchmark: 9.134377 },
  { date: "2023-12-31", thorNet: 6.216211, benchmark: 4.566267 },
  { date: "2024-01-31", thorNet: 1.945599, benchmark: 1.592653 },
  { date: "2024-02-29", thorNet: 7.144663, benchmark: 5.218689 },
  { date: "2024-03-31", thorNet: 4.424469, benchmark: 3.272387 },
  { date: "2024-04-30", thorNet: -5.358434, benchmark: -4.031949 },
  { date: "2024-05-31", thorNet: 4.473461, benchmark: 5.057998 },
  { date: "2024-06-30", thorNet: 4.741984, benchmark: 3.528453 },
  { date: "2024-07-31", thorNet: 1.371786, benchmark: 1.21094 },
  { date: "2024-08-31", thorNet: 4.537154, benchmark: 2.336572 },
  { date: "2024-09-30", thorNet: -0.938169, benchmark: 2.100923 },
  { date: "2024-10-31", thorNet: -1.048208, benchmark: -0.892376 },
  { date: "2024-11-30", thorNet: 6.440343, benchmark: 5.963334 },
  { date: "2024-12-31", thorNet: -3.504941, benchmark: -2.409987 },
  { date: "2025-01-31", thorNet: 2.248776, benchmark: 2.685644 },
  { date: "2025-02-28", thorNet: -1.064214, benchmark: -1.269465 },
  { date: "2025-03-31", thorNet: -4.477115, benchmark: -5.572105 },
  { date: "2025-04-30", thorNet: 3.308727, benchmark: -0.867054 },
  { date: "2025-05-31", thorNet: 8.70951, benchmark: 6.284508 },
  { date: "2025-06-30", thorNet: 7.166851, benchmark: 5.139351 },
  { date: "2025-07-31", thorNet: 3.048203, benchmark: 2.303126 },
  { date: "2025-08-31", thorNet: 2.689582, benchmark: 2.051923 },
  { date: "2025-09-30", thorNet: 4.931353, benchmark: 3.560633 },
  { date: "2025-10-31", thorNet: 3.154086, benchmark: 2.383721 },
  { date: "2025-11-30", thorNet: -1.983057, benchmark: 0.194988 },
  { date: "2025-12-31", thorNet: 0.154525, benchmark: 0.077168 },
  { date: "2026-01-31", thorNet: 1.203512, benchmark: 1.473756 },
  { date: "2026-02-28", thorNet: -0.59, benchmark: -0.8642 },
];

// ─── Helper functions ───

function compoundReturns(returns: number[]): number {
  let cumulative = 1;
  for (const r of returns) {
    cumulative *= 1 + r / 100;
  }
  return (cumulative - 1) * 100;
}

function annualizeReturn(totalReturnPct: number, months: number): number {
  const totalFactor = 1 + totalReturnPct / 100;
  const annualized = Math.pow(totalFactor, 12 / months) - 1;
  return annualized * 100;
}

// ─── Standard Period Returns ───
// All periods are derived from the END of the series (the as-of month):
// MTD = the as-of month; QTD/YTD = calendar quarter/year to the as-of month;
// trailing periods use exact 12/36/60/120-month windows.

function calcStandardPeriods() {
  const data = monthlyReturns;
  const lastDate = data[data.length - 1].date;
  const year = lastDate.slice(0, 4);
  const month = Number(lastDate.slice(5, 7));
  const quarterStartMonth = Math.floor((month - 1) / 3) * 3 + 1;
  const quarterStart = `${year}-${String(quarterStartMonth).padStart(2, "0")}-01`;
  const yearStart = `${year}-01-01`;

  const inPeriod = (start: string) => data.filter((d) => d.date >= start);

  const mtd = {
    thor: data[data.length - 1].thorNet,
    bench: data[data.length - 1].benchmark,
  };
  const qtd = {
    thor: compoundReturns(inPeriod(quarterStart).map((d) => d.thorNet)),
    bench: compoundReturns(inPeriod(quarterStart).map((d) => d.benchmark)),
  };
  const ytd = {
    thor: compoundReturns(inPeriod(yearStart).map((d) => d.thorNet)),
    bench: compoundReturns(inPeriod(yearStart).map((d) => d.benchmark)),
  };

  const oneYear = {
    thor: compoundReturns(data.slice(-12).map((d) => d.thorNet)),
    bench: compoundReturns(data.slice(-12).map((d) => d.benchmark)),
  };

  const threeYear = {
    thor: annualizeReturn(compoundReturns(data.slice(-36).map((d) => d.thorNet)), 36),
    bench: annualizeReturn(compoundReturns(data.slice(-36).map((d) => d.benchmark)), 36),
  };

  const fiveYear = {
    thor: annualizeReturn(compoundReturns(data.slice(-60).map((d) => d.thorNet)), 60),
    bench: annualizeReturn(compoundReturns(data.slice(-60).map((d) => d.benchmark)), 60),
  };

  const sinceInception = {
    thor: annualizeReturn(compoundReturns(data.map((d) => d.thorNet)), data.length),
    bench: annualizeReturn(compoundReturns(data.map((d) => d.benchmark)), data.length),
  };

  return {
    mtd,
    qtd,
    ytd,
    oneYear,
    threeYear,
    fiveYear,
    sinceInception,
  };
}

// ─── Calendar Year Returns ───

function calcCalendarYears() {
  const years = Array.from(new Set(monthlyReturns.map((d) => d.date.slice(0, 4)))).sort();
  return years.map((yearStr) => {
    const yearData = monthlyReturns.filter((d) => d.date.startsWith(`${yearStr}-`));
    return {
      year: Number(yearStr),
      thor: compoundReturns(yearData.map((d) => d.thorNet)),
      bench: compoundReturns(yearData.map((d) => d.benchmark)),
    };
  });
}

// ─── Growth of $10,000 ───

function calcGrowthOf10K() {
  let thorValue = 10000;
  let benchValue = 10000;

  for (const m of monthlyReturns) {
    thorValue *= 1 + m.thorNet / 100;
    benchValue *= 1 + m.benchmark / 100;
  }

  return {
    thor: Math.round(thorValue),
    bench: Math.round(benchValue),
  };
}

// ─── Risk Statistics ───

function calcRiskStats() {
  const thorReturns = monthlyReturns.map((d) => d.thorNet);
  const benchReturns = monthlyReturns.map((d) => d.benchmark);
  const n = thorReturns.length;

  const thorCumulative = compoundReturns(thorReturns);
  const benchCumulative = compoundReturns(benchReturns);
  const thorAnnReturn = annualizeReturn(thorCumulative, n);
  const benchAnnReturn = annualizeReturn(benchCumulative, n);

  const thorMean = thorReturns.reduce((a, b) => a + b, 0) / n;
  const benchMean = benchReturns.reduce((a, b) => a + b, 0) / n;
  const thorMonthlyStd = Math.sqrt(thorReturns.reduce((sum, r) => sum + (r - thorMean) ** 2, 0) / (n - 1));
  const benchMonthlyStd = Math.sqrt(benchReturns.reduce((sum, r) => sum + (r - benchMean) ** 2, 0) / (n - 1));
  const thorAnnStd = thorMonthlyStd * Math.sqrt(12);
  const benchAnnStd = benchMonthlyStd * Math.sqrt(12);

  // Sharpe Ratio (risk-free = 2% long-term average)
  const riskFree = 2.0;
  const thorSharpe = (thorAnnReturn - riskFree) / thorAnnStd;
  const benchSharpe = (benchAnnReturn - riskFree) / benchAnnStd;

  function maxDrawdown(returns: number[]): number {
    let peak = 1;
    let cumulative = 1;
    let maxDD = 0;
    for (const r of returns) {
      cumulative *= 1 + r / 100;
      if (cumulative > peak) peak = cumulative;
      const dd = (cumulative - peak) / peak;
      if (dd < maxDD) maxDD = dd;
    }
    return maxDD * 100;
  }

  const thorMaxDD = maxDrawdown(thorReturns);
  const benchMaxDD = maxDrawdown(benchReturns);

  const thorBest = Math.max(...thorReturns);
  const thorWorst = Math.min(...thorReturns);
  const benchBest = Math.max(...benchReturns);
  const benchWorst = Math.min(...benchReturns);

  const thorPositive = (thorReturns.filter((r) => r > 0).length / n) * 100;
  const benchPositive = (benchReturns.filter((r) => r > 0).length / n) * 100;

  return {
    annualizedReturn: { thor: thorAnnReturn, bench: benchAnnReturn },
    annualizedStdDev: { thor: thorAnnStd, bench: benchAnnStd },
    sharpeRatio: { thor: thorSharpe, bench: benchSharpe },
    maxDrawdown: { thor: thorMaxDD, bench: benchMaxDD },
    bestMonth: { thor: thorBest, bench: benchBest },
    worstMonth: { thor: thorWorst, bench: benchWorst },
    positiveMonths: { thor: thorPositive, bench: benchPositive },
  };
}

// ─── Export all computed data ───

export const standardPeriods = calcStandardPeriods();
export const calendarYears = calcCalendarYears();
export const growthOf10K = calcGrowthOf10K();
export const riskStats = calcRiskStats();
