// THOR Low Volatility SDQ model performance data
// GENERATED by ~/clawd/scripts/update-model-performance.mjs — do not hand-edit.
// Generated: 2026-06-10T15:13:22.554Z
// Source of truth: data/performance/low-volatility-sdq.csv
// All returns are monthly percentages. NET returns used throughout.
// Coverage: January 2017 through May 2026 (complete months only).

export interface MonthlyReturn {
  date: string; // YYYY-MM-DD (calendar month end)
  thorNet: number; // monthly return in %
  benchmark: number; // monthly return in %
}

export const monthlyReturns: MonthlyReturn[] = [
  { date: "2017-01-31", thorNet: 2.443908, benchmark: 1.789447 },
  { date: "2017-02-28", thorNet: 4.41583, benchmark: 3.929161 },
  { date: "2017-03-31", thorNet: 0.517378, benchmark: 0.125799 },
  { date: "2017-04-30", thorNet: 1.700305, benchmark: 0.992615 },
  { date: "2017-05-31", thorNet: 2.029174, benchmark: 1.41128 },
  { date: "2017-06-30", thorNet: -0.086202, benchmark: 0.637457 },
  { date: "2017-07-31", thorNet: 2.912546, benchmark: 2.055419 },
  { date: "2017-08-31", thorNet: 1.002412, benchmark: 0.291764 },
  { date: "2017-09-30", thorNet: 1.211445, benchmark: 2.014095 },
  { date: "2017-10-31", thorNet: 3.784382, benchmark: 2.356438 },
  { date: "2017-11-30", thorNet: 2.99932, benchmark: 3.056568 },
  { date: "2017-12-31", thorNet: 1.264571, benchmark: 1.208672 },
  { date: "2018-01-31", thorNet: 6.690289, benchmark: 5.635923 },
  { date: "2018-02-28", thorNet: -4.752784, benchmark: -3.635993 },
  { date: "2018-03-31", thorNet: -0.01694, benchmark: -2.741579 },
  { date: "2018-04-30", thorNet: -0.016393, benchmark: 0.51682 },
  { date: "2018-05-31", thorNet: -0.01694, benchmark: 2.430923 },
  { date: "2018-06-30", thorNet: -1.095977, benchmark: 0.575507 },
  { date: "2018-07-31", thorNet: 1.364306, benchmark: 3.704656 },
  { date: "2018-08-31", thorNet: 2.67462, benchmark: 3.191981 },
  { date: "2018-09-30", thorNet: 0.138228, benchmark: 0.594853 },
  { date: "2018-10-31", thorNet: -4.028758, benchmark: -6.910433 },
  { date: "2018-11-30", thorNet: -0.016393, benchmark: 1.854931 },
  { date: "2018-12-31", thorNet: -0.01694, benchmark: -8.793624 },
  { date: "2019-01-31", thorNet: 3.514059, benchmark: 8.006569 },
  { date: "2019-02-28", thorNet: 3.341061, benchmark: 3.241576 },
  { date: "2019-03-31", thorNet: 1.935426, benchmark: 1.807903 },
  { date: "2019-04-30", thorNet: 4.040584, benchmark: 4.085252 },
  { date: "2019-05-31", thorNet: -6.97297, benchmark: -6.37712 },
  { date: "2019-06-30", thorNet: 6.48486, benchmark: 6.959258 },
  { date: "2019-07-31", thorNet: 1.611363, benchmark: 1.511943 },
  { date: "2019-08-31", thorNet: -1.680053, benchmark: -1.674358 },
  { date: "2019-09-30", thorNet: 2.013929, benchmark: 1.947881 },
  { date: "2019-10-31", thorNet: 1.34694, benchmark: 2.210456 },
  { date: "2019-11-30", thorNet: 3.880773, benchmark: 3.61982 },
  { date: "2019-12-31", thorNet: 2.815745, benchmark: 2.903361 },
  { date: "2020-01-31", thorNet: 0.694975, benchmark: -0.040376 },
  { date: "2020-02-29", thorNet: -7.764775, benchmark: -7.916571 },
  { date: "2020-03-31", thorNet: 5.933212, benchmark: -12.464273 },
  { date: "2020-04-30", thorNet: 17.903249, benchmark: 12.698333 },
  { date: "2020-05-31", thorNet: 5.320056, benchmark: 4.76452 },
  { date: "2020-06-30", thorNet: 3.836998, benchmark: 1.776045 },
  { date: "2020-07-31", thorNet: 6.543744, benchmark: 5.889196 },
  { date: "2020-08-31", thorNet: 8.002975, benchmark: 6.979655 },
  { date: "2020-09-30", thorNet: -5.500715, benchmark: -3.739835 },
  { date: "2020-10-31", thorNet: -0.01694, benchmark: -2.493327 },
  { date: "2020-11-30", thorNet: -0.016393, benchmark: 10.877677 },
  { date: "2020-12-31", thorNet: 2.392134, benchmark: 3.706598 },
  { date: "2021-01-31", thorNet: -1.030936, benchmark: -1.019052 },
  { date: "2021-02-28", thorNet: 1.962962, benchmark: 2.780556 },
  { date: "2021-03-31", thorNet: 4.856078, benchmark: 4.540527 },
  { date: "2021-04-30", thorNet: 3.75448, benchmark: 5.291029 },
  { date: "2021-05-31", thorNet: 0.092475, benchmark: 0.656623 },
  { date: "2021-06-30", thorNet: 1.069339, benchmark: 2.247293 },
  { date: "2021-07-31", thorNet: 1.87091, benchmark: 2.441267 },
  { date: "2021-08-31", thorNet: 2.177573, benchmark: 2.975983 },
  { date: "2021-09-30", thorNet: -4.413132, benchmark: -4.657525 },
  { date: "2021-10-31", thorNet: 6.388769, benchmark: 7.016357 },
  { date: "2021-11-30", thorNet: -0.790384, benchmark: -0.803504 },
  { date: "2021-12-31", thorNet: 3.884435, benchmark: 4.629499 },
  { date: "2022-01-31", thorNet: -7.293543, benchmark: -5.274114 },
  { date: "2022-02-28", thorNet: -0.015301, benchmark: -2.951687 },
  { date: "2022-03-31", thorNet: 1.504735, benchmark: 3.755553 },
  { date: "2022-04-30", thorNet: -6.423787, benchmark: -8.776879 },
  { date: "2022-05-31", thorNet: -0.01694, benchmark: 0.22574 },
  { date: "2022-06-30", thorNet: -4.662503, benchmark: -8.246916 },
  { date: "2022-07-31", thorNet: 7.561623, benchmark: 9.208742 },
  { date: "2022-08-31", thorNet: -3.775038, benchmark: -4.080216 },
  { date: "2022-09-30", thorNet: -0.824724, benchmark: -9.241646 },
  { date: "2022-10-31", thorNet: 1.402476, benchmark: 8.12757 },
  { date: "2022-11-30", thorNet: 7.904765, benchmark: 5.559141 },
  { date: "2022-12-31", thorNet: -6.61186, benchmark: -5.75758 },
  { date: "2023-01-31", thorNet: 4.566316, benchmark: 6.288742 },
  { date: "2023-02-28", thorNet: -2.292377, benchmark: -2.514273 },
  { date: "2023-03-31", thorNet: 5.087854, benchmark: 3.712488 },
  { date: "2023-04-30", thorNet: 1.49336, benchmark: 1.597486 },
  { date: "2023-05-31", thorNet: 1.869419, benchmark: 0.461635 },
  { date: "2023-06-30", thorNet: 5.764881, benchmark: 6.481419 },
  { date: "2023-07-31", thorNet: 3.507928, benchmark: 3.273281 },
  { date: "2023-08-31", thorNet: -2.409819, benchmark: -1.625209 },
  { date: "2023-09-30", thorNet: -4.03251, benchmark: -4.739335 },
  { date: "2023-10-31", thorNet: -1.738772, benchmark: -2.170853 },
  { date: "2023-11-30", thorNet: 5.387101, benchmark: 9.134377 },
  { date: "2023-12-31", thorNet: 4.967284, benchmark: 4.566267 },
  { date: "2024-01-31", thorNet: 1.522562, benchmark: 1.592653 },
  { date: "2024-02-29", thorNet: 4.251658, benchmark: 5.218689 },
  { date: "2024-03-31", thorNet: 2.221461, benchmark: 3.272387 },
  { date: "2024-04-30", thorNet: -4.942628, benchmark: -4.031949 },
  { date: "2024-05-31", thorNet: 3.764017, benchmark: 5.057998 },
  { date: "2024-06-30", thorNet: 2.390707, benchmark: 3.528453 },
  { date: "2024-07-31", thorNet: 1.145883, benchmark: 1.21094 },
  { date: "2024-08-31", thorNet: -5.369847, benchmark: 2.336572 },
  { date: "2024-09-30", thorNet: 1.4758, benchmark: 2.100923 },
  { date: "2024-10-31", thorNet: -1.166009, benchmark: -0.892376 },
  { date: "2024-11-30", thorNet: 6.442757, benchmark: 5.963334 },
  { date: "2024-12-31", thorNet: -2.434149, benchmark: -2.409987 },
  { date: "2025-01-31", thorNet: 3.161737, benchmark: 2.685644 },
  { date: "2025-02-28", thorNet: -1.820526, benchmark: -1.269465 },
  { date: "2025-03-31", thorNet: -4.323464, benchmark: -5.572105 },
  { date: "2025-04-30", thorNet: 0.009926, benchmark: -0.867054 },
  { date: "2025-05-31", thorNet: 6.487979, benchmark: 6.284508 },
  { date: "2025-06-30", thorNet: 5.30737, benchmark: 5.139351 },
  { date: "2025-07-31", thorNet: 1.651448, benchmark: 2.303126 },
  { date: "2025-08-31", thorNet: 2.05318, benchmark: 2.051923 },
  { date: "2025-09-30", thorNet: 3.649201, benchmark: 3.560633 },
  { date: "2025-10-31", thorNet: 3.263481, benchmark: 2.383721 },
  { date: "2025-11-30", thorNet: -0.511803, benchmark: 0.194988 },
  { date: "2025-12-31", thorNet: 0.484109, benchmark: 0.077168 },
  { date: "2026-01-31", thorNet: 1.593196, benchmark: 1.473756 },
  { date: "2026-02-28", thorNet: -0.29, benchmark: -0.8642 },
  { date: "2026-03-31", thorNet: -5.008188, benchmark: -4.937955 },
  { date: "2026-04-30", thorNet: 4.23813, benchmark: 10.505265 },
  { date: "2026-05-31", thorNet: 7.8207, benchmark: 5.262573 },
];

// ─── Helper functions ───

function compoundReturns(returns: number[]): number {
  let cumulative = 1;
  for (const r of returns) {
    cumulative *= 1 + r / 100;
  }
  return (cumulative - 1) * 100;
}

function annualizeReturn(totalReturnPct: number, months: number): number {
  const totalFactor = 1 + totalReturnPct / 100;
  const annualized = Math.pow(totalFactor, 12 / months) - 1;
  return annualized * 100;
}

// ─── Standard Period Returns ───
// All periods are derived from the END of the series (the as-of month):
// MTD = the as-of month; QTD/YTD = calendar quarter/year to the as-of month;
// trailing periods use exact 12/36/60/120-month windows.

function calcStandardPeriods() {
  const data = monthlyReturns;
  const lastDate = data[data.length - 1].date;
  const year = lastDate.slice(0, 4);
  const month = Number(lastDate.slice(5, 7));
  const quarterStartMonth = Math.floor((month - 1) / 3) * 3 + 1;
  const quarterStart = `${year}-${String(quarterStartMonth).padStart(2, "0")}-01`;
  const yearStart = `${year}-01-01`;

  const inPeriod = (start: string) => data.filter((d) => d.date >= start);

  const mtd = {
    thor: data[data.length - 1].thorNet,
    bench: data[data.length - 1].benchmark,
  };
  const qtd = {
    thor: compoundReturns(inPeriod(quarterStart).map((d) => d.thorNet)),
    bench: compoundReturns(inPeriod(quarterStart).map((d) => d.benchmark)),
  };
  const ytd = {
    thor: compoundReturns(inPeriod(yearStart).map((d) => d.thorNet)),
    bench: compoundReturns(inPeriod(yearStart).map((d) => d.benchmark)),
  };

  const oneYear = {
    thor: compoundReturns(data.slice(-12).map((d) => d.thorNet)),
    bench: compoundReturns(data.slice(-12).map((d) => d.benchmark)),
  };

  const threeYear = {
    thor: annualizeReturn(compoundReturns(data.slice(-36).map((d) => d.thorNet)), 36),
    bench: annualizeReturn(compoundReturns(data.slice(-36).map((d) => d.benchmark)), 36),
  };

  const fiveYear = {
    thor: annualizeReturn(compoundReturns(data.slice(-60).map((d) => d.thorNet)), 60),
    bench: annualizeReturn(compoundReturns(data.slice(-60).map((d) => d.benchmark)), 60),
  };

  const sinceInception = {
    thor: annualizeReturn(compoundReturns(data.map((d) => d.thorNet)), data.length),
    bench: annualizeReturn(compoundReturns(data.map((d) => d.benchmark)), data.length),
  };

  return {
    mtd,
    qtd,
    ytd,
    oneYear,
    threeYear,
    fiveYear,
    sinceInception,
  };
}

// ─── Calendar Year Returns ───

function calcCalendarYears() {
  const years = Array.from(new Set(monthlyReturns.map((d) => d.date.slice(0, 4)))).sort();
  return years.map((yearStr) => {
    const yearData = monthlyReturns.filter((d) => d.date.startsWith(`${yearStr}-`));
    return {
      year: Number(yearStr),
      thor: compoundReturns(yearData.map((d) => d.thorNet)),
      bench: compoundReturns(yearData.map((d) => d.benchmark)),
    };
  });
}

// ─── Growth of $10,000 ───

function calcGrowthOf10K() {
  let thorValue = 10000;
  let benchValue = 10000;

  for (const m of monthlyReturns) {
    thorValue *= 1 + m.thorNet / 100;
    benchValue *= 1 + m.benchmark / 100;
  }

  return {
    thor: Math.round(thorValue),
    bench: Math.round(benchValue),
  };
}

// ─── Risk Statistics ───

function calcRiskStats() {
  const thorReturns = monthlyReturns.map((d) => d.thorNet);
  const benchReturns = monthlyReturns.map((d) => d.benchmark);
  const n = thorReturns.length;

  const thorCumulative = compoundReturns(thorReturns);
  const benchCumulative = compoundReturns(benchReturns);
  const thorAnnReturn = annualizeReturn(thorCumulative, n);
  const benchAnnReturn = annualizeReturn(benchCumulative, n);

  const thorMean = thorReturns.reduce((a, b) => a + b, 0) / n;
  const benchMean = benchReturns.reduce((a, b) => a + b, 0) / n;
  const thorMonthlyStd = Math.sqrt(thorReturns.reduce((sum, r) => sum + (r - thorMean) ** 2, 0) / (n - 1));
  const benchMonthlyStd = Math.sqrt(benchReturns.reduce((sum, r) => sum + (r - benchMean) ** 2, 0) / (n - 1));
  const thorAnnStd = thorMonthlyStd * Math.sqrt(12);
  const benchAnnStd = benchMonthlyStd * Math.sqrt(12);

  // Sharpe Ratio (risk-free = 2% long-term average)
  const riskFree = 2.0;
  const thorSharpe = (thorAnnReturn - riskFree) / thorAnnStd;
  const benchSharpe = (benchAnnReturn - riskFree) / benchAnnStd;

  function maxDrawdown(returns: number[]): number {
    let peak = 1;
    let cumulative = 1;
    let maxDD = 0;
    for (const r of returns) {
      cumulative *= 1 + r / 100;
      if (cumulative > peak) peak = cumulative;
      const dd = (cumulative - peak) / peak;
      if (dd < maxDD) maxDD = dd;
    }
    return maxDD * 100;
  }

  const thorMaxDD = maxDrawdown(thorReturns);
  const benchMaxDD = maxDrawdown(benchReturns);

  const thorBest = Math.max(...thorReturns);
  const thorWorst = Math.min(...thorReturns);
  const benchBest = Math.max(...benchReturns);
  const benchWorst = Math.min(...benchReturns);

  const thorPositive = (thorReturns.filter((r) => r > 0).length / n) * 100;
  const benchPositive = (benchReturns.filter((r) => r > 0).length / n) * 100;

  return {
    annualizedReturn: { thor: thorAnnReturn, bench: benchAnnReturn },
    annualizedStdDev: { thor: thorAnnStd, bench: benchAnnStd },
    sharpeRatio: { thor: thorSharpe, bench: benchSharpe },
    maxDrawdown: { thor: thorMaxDD, bench: benchMaxDD },
    bestMonth: { thor: thorBest, bench: benchBest },
    worstMonth: { thor: thorWorst, bench: benchWorst },
    positiveMonths: { thor: thorPositive, bench: benchPositive },
  };
}

// ─── Export all computed data ───

export const standardPeriods = calcStandardPeriods();
export const calendarYears = calcCalendarYears();
export const growthOf10K = calcGrowthOf10K();
export const riskStats = calcRiskStats();
