// THOR NextGen Stock model performance data
// GENERATED by ~/clawd/scripts/update-model-performance.mjs — do not hand-edit.
// Generated: 2026-06-10T15:13:22.554Z
// Source of truth: data/performance/nextgen-stock.csv
// All returns are monthly percentages. NET returns used throughout.
// Coverage: January 2020 through February 2026 (complete months only).

export interface MonthlyReturn {
  date: string; // YYYY-MM-DD (calendar month end)
  thorNet: number; // monthly return in %
  benchmark: number; // monthly return in %
}

export const monthlyReturns: MonthlyReturn[] = [
  { date: "2020-01-31", thorNet: 16.512418, benchmark: 3.496511 },
  { date: "2020-02-29", thorNet: 2.357502, benchmark: 2.007701 },
  { date: "2020-03-31", thorNet: -6.204933, benchmark: -16.729705 },
  { date: "2020-04-30", thorNet: 33.347176, benchmark: 25.750006 },
  { date: "2020-05-31", thorNet: 9.609414, benchmark: 13.536971 },
  { date: "2020-06-30", thorNet: 26.757738, benchmark: 13.514803 },
  { date: "2020-07-31", thorNet: 8.868164, benchmark: 12.705117 },
  { date: "2020-08-31", thorNet: 12.514195, benchmark: 18.613912 },
  { date: "2020-09-30", thorNet: 1.418377, benchmark: -3.493165 },
  { date: "2020-10-31", thorNet: 4.005553, benchmark: -1.315191 },
  { date: "2020-11-30", thorNet: 11.556105, benchmark: 23.769109 },
  { date: "2020-12-31", thorNet: 2.659433, benchmark: 12.607537 },
  { date: "2021-01-31", thorNet: 0.97504, benchmark: 10.40239 },
  { date: "2021-02-28", thorNet: -6.618902, benchmark: -5.151332 },
  { date: "2021-03-31", thorNet: -0.021462, benchmark: -7.985602 },
  { date: "2021-04-30", thorNet: 1.093949, benchmark: 0.683605 },
  { date: "2021-05-31", thorNet: -2.651516, benchmark: -7.178913 },
  { date: "2021-06-30", thorNet: 21.628949, benchmark: 16.66369 },
  { date: "2021-07-31", thorNet: -13.943476, benchmark: -8.242838 },
  { date: "2021-08-31", thorNet: -0.203034, benchmark: 1.691654 },
  { date: "2021-09-30", thorNet: -6.084328, benchmark: -9.423934 },
  { date: "2021-10-31", thorNet: 4.526376, benchmark: 9.725851 },
  { date: "2021-11-30", thorNet: 3.706936, benchmark: -12.854561 },
  { date: "2021-12-31", thorNet: -10.129038, benchmark: -9.755989 },
  { date: "2022-01-31", thorNet: -5.326292, benchmark: -20.255863 },
  { date: "2022-02-28", thorNet: -0.015301, benchmark: -6.575635 },
  { date: "2022-03-31", thorNet: -3.538085, benchmark: -5.931621 },
  { date: "2022-04-30", thorNet: -5.057198, benchmark: -28.903292 },
  { date: "2022-05-31", thorNet: -6.983654, benchmark: -6.450234 },
  { date: "2022-06-30", thorNet: -13.99769, benchmark: -9.548653 },
  { date: "2022-07-31", thorNet: -0.01694, benchmark: 13.164489 },
  { date: "2022-08-31", thorNet: -10.407294, benchmark: -7.20141 },
  { date: "2022-09-30", thorNet: -3.080223, benchmark: -9.909293 },
  { date: "2022-10-31", thorNet: -5.085387, benchmark: 1.457728 },
  { date: "2022-11-30", thorNet: -3.300649, benchmark: -2.089812 },
  { date: "2022-12-31", thorNet: -13.14695, benchmark: -16.648867 },
  { date: "2023-01-31", thorNet: 22.148962, benchmark: 27.816904 },
  { date: "2023-02-28", thorNet: 9.521601, benchmark: -0.776359 },
  { date: "2023-03-31", thorNet: 3.905747, benchmark: 1.817291 },
  { date: "2023-04-30", thorNet: -0.039474, benchmark: -10.956882 },
  { date: "2023-05-31", thorNet: 8.323416, benchmark: 12.722736 },
  { date: "2023-06-30", thorNet: 3.397631, benchmark: 9.014542 },
  { date: "2023-07-31", thorNet: 5.758209, benchmark: 14.29539 },
  { date: "2023-08-31", thorNet: -17.014316, benchmark: -13.280461 },
  { date: "2023-09-30", thorNet: 0.374319, benchmark: -9.32572 },
  { date: "2023-10-31", thorNet: 0.405617, benchmark: -11.570454 },
  { date: "2023-11-30", thorNet: 11.314298, benchmark: 31.442432 },
  { date: "2023-12-31", thorNet: 8.751385, benchmark: 13.576216 },
  { date: "2024-01-31", thorNet: -2.960359, benchmark: -13.290058 },
  { date: "2024-02-29", thorNet: 15.985473, benchmark: 12.860597 },
  { date: "2024-03-31", thorNet: 1.363956, benchmark: -2.282935 },
  { date: "2024-04-30", thorNet: 0.406784, benchmark: -13.218866 },
  { date: "2024-05-31", thorNet: 0.430661, benchmark: -2.323964 },
  { date: "2024-06-30", thorNet: -7.760876, benchmark: 3.533586 },
  { date: "2024-07-31", thorNet: 12.126667, benchmark: 3.594988 },
  { date: "2024-08-31", thorNet: 0.435787, benchmark: -1.559414 },
  { date: "2024-09-30", thorNet: 0.397381, benchmark: 6.046407 },
  { date: "2024-10-31", thorNet: 0.370185, benchmark: -3.450468 },
  { date: "2024-11-30", thorNet: 15.375597, benchmark: 26.345604 },
  { date: "2024-12-31", thorNet: -7.973832, benchmark: -2.086935 },
  { date: "2025-01-31", thorNet: 4.746669, benchmark: 10.745111 },
  { date: "2025-02-28", thorNet: -8.722378, benchmark: -11.49992 },
  { date: "2025-03-31", thorNet: -10.687141, benchmark: -14.485996 },
  { date: "2025-04-30", thorNet: 2.929991, benchmark: 6.851665 },
  { date: "2025-05-31", thorNet: 13.409299, benchmark: 10.877229 },
  { date: "2025-06-30", thorNet: 10.422298, benchmark: 24.693983 },
  { date: "2025-07-31", thorNet: 9.313018, benchmark: 7.170325 },
  { date: "2025-08-31", thorNet: 8.215325, benchmark: -0.491185 },
  { date: "2025-09-30", thorNet: 13.217832, benchmark: 15.128069 },
  { date: "2025-10-31", thorNet: 3.210009, benchmark: 3.105457 },
  { date: "2025-11-30", thorNet: -10.930324, benchmark: -10.451786 },
  { date: "2025-12-31", thorNet: 0.318915, benchmark: -3.463882 },
  { date: "2026-01-31", thorNet: 0.278483, benchmark: -2.665107 },
  { date: "2026-02-28", thorNet: -0.3, benchmark: -2.6179 },
];

// ─── Helper functions ───

function compoundReturns(returns: number[]): number {
  let cumulative = 1;
  for (const r of returns) {
    cumulative *= 1 + r / 100;
  }
  return (cumulative - 1) * 100;
}

function annualizeReturn(totalReturnPct: number, months: number): number {
  const totalFactor = 1 + totalReturnPct / 100;
  const annualized = Math.pow(totalFactor, 12 / months) - 1;
  return annualized * 100;
}

// ─── Standard Period Returns ───
// All periods are derived from the END of the series (the as-of month):
// MTD = the as-of month; QTD/YTD = calendar quarter/year to the as-of month;
// trailing periods use exact 12/36/60/120-month windows.

function calcStandardPeriods() {
  const data = monthlyReturns;
  const lastDate = data[data.length - 1].date;
  const year = lastDate.slice(0, 4);
  const month = Number(lastDate.slice(5, 7));
  const quarterStartMonth = Math.floor((month - 1) / 3) * 3 + 1;
  const quarterStart = `${year}-${String(quarterStartMonth).padStart(2, "0")}-01`;
  const yearStart = `${year}-01-01`;

  const inPeriod = (start: string) => data.filter((d) => d.date >= start);

  const mtd = {
    thor: data[data.length - 1].thorNet,
    bench: data[data.length - 1].benchmark,
  };
  const qtd = {
    thor: compoundReturns(inPeriod(quarterStart).map((d) => d.thorNet)),
    bench: compoundReturns(inPeriod(quarterStart).map((d) => d.benchmark)),
  };
  const ytd = {
    thor: compoundReturns(inPeriod(yearStart).map((d) => d.thorNet)),
    bench: compoundReturns(inPeriod(yearStart).map((d) => d.benchmark)),
  };

  const oneYear = {
    thor: compoundReturns(data.slice(-12).map((d) => d.thorNet)),
    bench: compoundReturns(data.slice(-12).map((d) => d.benchmark)),
  };

  const threeYear = {
    thor: annualizeReturn(compoundReturns(data.slice(-36).map((d) => d.thorNet)), 36),
    bench: annualizeReturn(compoundReturns(data.slice(-36).map((d) => d.benchmark)), 36),
  };

  const fiveYear = {
    thor: annualizeReturn(compoundReturns(data.slice(-60).map((d) => d.thorNet)), 60),
    bench: annualizeReturn(compoundReturns(data.slice(-60).map((d) => d.benchmark)), 60),
  };

  const sinceInception = {
    thor: annualizeReturn(compoundReturns(data.map((d) => d.thorNet)), data.length),
    bench: annualizeReturn(compoundReturns(data.map((d) => d.benchmark)), data.length),
  };

  return {
    mtd,
    qtd,
    ytd,
    oneYear,
    threeYear,
    fiveYear,
    sinceInception,
  };
}

// ─── Calendar Year Returns ───

function calcCalendarYears() {
  const years = Array.from(new Set(monthlyReturns.map((d) => d.date.slice(0, 4)))).sort();
  return years.map((yearStr) => {
    const yearData = monthlyReturns.filter((d) => d.date.startsWith(`${yearStr}-`));
    return {
      year: Number(yearStr),
      thor: compoundReturns(yearData.map((d) => d.thorNet)),
      bench: compoundReturns(yearData.map((d) => d.benchmark)),
    };
  });
}

// ─── Growth of $10,000 ───

function calcGrowthOf10K() {
  let thorValue = 10000;
  let benchValue = 10000;

  for (const m of monthlyReturns) {
    thorValue *= 1 + m.thorNet / 100;
    benchValue *= 1 + m.benchmark / 100;
  }

  return {
    thor: Math.round(thorValue),
    bench: Math.round(benchValue),
  };
}

// ─── Risk Statistics ───

function calcRiskStats() {
  const thorReturns = monthlyReturns.map((d) => d.thorNet);
  const benchReturns = monthlyReturns.map((d) => d.benchmark);
  const n = thorReturns.length;

  const thorCumulative = compoundReturns(thorReturns);
  const benchCumulative = compoundReturns(benchReturns);
  const thorAnnReturn = annualizeReturn(thorCumulative, n);
  const benchAnnReturn = annualizeReturn(benchCumulative, n);

  const thorMean = thorReturns.reduce((a, b) => a + b, 0) / n;
  const benchMean = benchReturns.reduce((a, b) => a + b, 0) / n;
  const thorMonthlyStd = Math.sqrt(thorReturns.reduce((sum, r) => sum + (r - thorMean) ** 2, 0) / (n - 1));
  const benchMonthlyStd = Math.sqrt(benchReturns.reduce((sum, r) => sum + (r - benchMean) ** 2, 0) / (n - 1));
  const thorAnnStd = thorMonthlyStd * Math.sqrt(12);
  const benchAnnStd = benchMonthlyStd * Math.sqrt(12);

  // Sharpe Ratio (risk-free = 2% long-term average)
  const riskFree = 2.0;
  const thorSharpe = (thorAnnReturn - riskFree) / thorAnnStd;
  const benchSharpe = (benchAnnReturn - riskFree) / benchAnnStd;

  function maxDrawdown(returns: number[]): number {
    let peak = 1;
    let cumulative = 1;
    let maxDD = 0;
    for (const r of returns) {
      cumulative *= 1 + r / 100;
      if (cumulative > peak) peak = cumulative;
      const dd = (cumulative - peak) / peak;
      if (dd < maxDD) maxDD = dd;
    }
    return maxDD * 100;
  }

  const thorMaxDD = maxDrawdown(thorReturns);
  const benchMaxDD = maxDrawdown(benchReturns);

  const thorBest = Math.max(...thorReturns);
  const thorWorst = Math.min(...thorReturns);
  const benchBest = Math.max(...benchReturns);
  const benchWorst = Math.min(...benchReturns);

  const thorPositive = (thorReturns.filter((r) => r > 0).length / n) * 100;
  const benchPositive = (benchReturns.filter((r) => r > 0).length / n) * 100;

  return {
    annualizedReturn: { thor: thorAnnReturn, bench: benchAnnReturn },
    annualizedStdDev: { thor: thorAnnStd, bench: benchAnnStd },
    sharpeRatio: { thor: thorSharpe, bench: benchSharpe },
    maxDrawdown: { thor: thorMaxDD, bench: benchMaxDD },
    bestMonth: { thor: thorBest, bench: benchBest },
    worstMonth: { thor: thorWorst, bench: benchWorst },
    positiveMonths: { thor: thorPositive, bench: benchPositive },
  };
}

// ─── Export all computed data ───

export const standardPeriods = calcStandardPeriods();
export const calendarYears = calcCalendarYears();
export const growthOf10K = calcGrowthOf10K();
export const riskStats = calcRiskStats();
