// THOR Sector 100 model performance data
// GENERATED by ~/clawd/scripts/update-model-performance.mjs — do not hand-edit.
// Generated: 2026-06-10T15:13:22.553Z
// Source of truth: data/performance/sector-100.csv
// All returns are monthly percentages. NET returns used throughout.
// Coverage: February 2005 through May 2026 (complete months only).

export interface MonthlyReturn {
  date: string; // YYYY-MM-DD (calendar month end)
  thorNet: number; // monthly return in %
  benchmark: number; // monthly return in %
}

export const monthlyReturns: MonthlyReturn[] = [
  { date: "2005-02-28", thorNet: 1.301927, benchmark: 0.225647 },
  { date: "2005-03-31", thorNet: -1.196732, benchmark: -1.363688 },
  { date: "2005-04-30", thorNet: -0.160964, benchmark: -3.195052 },
  { date: "2005-05-31", thorNet: 0.850464, benchmark: 4.495754 },
  { date: "2005-06-30", thorNet: -0.42929, benchmark: 1.536061 },
  { date: "2005-07-31", thorNet: 3.648322, benchmark: 5.107137 },
  { date: "2005-08-31", thorNet: -0.757645, benchmark: -0.8729 },
  { date: "2005-09-30", thorNet: 1.856774, benchmark: 0.496474 },
  { date: "2005-10-31", thorNet: -3.558118, benchmark: -2.678643 },
  { date: "2005-11-30", thorNet: 4.237357, benchmark: 4.551486 },
  { date: "2005-12-31", thorNet: 0.483621, benchmark: 0.53291 },
  { date: "2006-01-31", thorNet: 2.751113, benchmark: 4.025795 },
  { date: "2006-02-28", thorNet: -0.043565, benchmark: 0.33604 },
  { date: "2006-03-31", thorNet: 2.383019, benchmark: 2.096463 },
  { date: "2006-04-30", thorNet: 0.212866, benchmark: 0.861687 },
  { date: "2006-05-31", thorNet: -3.368575, benchmark: -2.967618 },
  { date: "2006-06-30", thorNet: -0.164094, benchmark: -0.279064 },
  { date: "2006-07-31", thorNet: -0.027658, benchmark: -1.328366 },
  { date: "2006-08-31", thorNet: 1.650942, benchmark: 2.739696 },
  { date: "2006-09-30", thorNet: 1.904215, benchmark: 2.396081 },
  { date: "2006-10-31", thorNet: 3.734048, benchmark: 3.75956 },
  { date: "2006-11-30", thorNet: 2.249031, benchmark: 2.495115 },
  { date: "2006-12-31", thorNet: 0.603087, benchmark: 0.565536 },
  { date: "2007-01-31", thorNet: 2.141383, benchmark: 2.408135 },
  { date: "2007-02-28", thorNet: -1.058194, benchmark: -0.474422 },
  { date: "2007-03-31", thorNet: 0.915972, benchmark: 0.819957 },
  { date: "2007-04-30", thorNet: 3.730213, benchmark: 4.412542 },
  { date: "2007-05-31", thorNet: 3.259856, benchmark: 3.235353 },
  { date: "2007-06-30", thorNet: -1.38323, benchmark: -1.855832 },
  { date: "2007-07-31", thorNet: -2.39098, benchmark: -4.511716 },
  { date: "2007-08-31", thorNet: 0.452162, benchmark: 0.081818 },
  { date: "2007-09-30", thorNet: 3.785446, benchmark: 2.490357 },
  { date: "2007-10-31", thorNet: 2.271394, benchmark: 1.120222 },
  { date: "2007-11-30", thorNet: -1.441876, benchmark: -4.648865 },
  { date: "2007-12-31", thorNet: 0.817894, benchmark: -1.71526 },
  { date: "2008-01-31", thorNet: -2.503242, benchmark: -4.30267 },
  { date: "2008-02-29", thorNet: -0.268072, benchmark: -3.01219 },
  { date: "2008-03-31", thorNet: 2.107927, benchmark: -1.863931 },
  { date: "2008-04-30", thorNet: 2.394012, benchmark: 5.722964 },
  { date: "2008-05-31", thorNet: -0.668441, benchmark: 2.651374 },
  { date: "2008-06-30", thorNet: -4.558948, benchmark: -9.836152 },
  { date: "2008-07-31", thorNet: -2.606076, benchmark: -0.503115 },
  { date: "2008-08-31", thorNet: 0.49028, benchmark: 2.961721 },
  { date: "2008-09-30", thorNet: -3.125372, benchmark: -10.908621 },
  { date: "2008-10-31", thorNet: -6.010717, benchmark: -20.906879 },
  { date: "2008-11-30", thorNet: 4.946568, benchmark: -9.633343 },
  { date: "2008-12-31", thorNet: 3.61108, benchmark: 3.083049 },
  { date: "2009-01-31", thorNet: -9.761184, benchmark: -8.345317 },
  { date: "2009-02-28", thorNet: -11.074914, benchmark: -11.245695 },
  { date: "2009-03-31", thorNet: 6.654589, benchmark: 10.291002 },
  { date: "2009-04-30", thorNet: 13.181852, benchmark: 18.69195 },
  { date: "2009-05-31", thorNet: 5.4214, benchmark: 6.462566 },
  { date: "2009-06-30", thorNet: -0.634552, benchmark: -1.198619 },
  { date: "2009-07-31", thorNet: 7.987754, benchmark: 9.18533 },
  { date: "2009-08-31", thorNet: 4.496689, benchmark: 5.648064 },
  { date: "2009-09-30", thorNet: 3.915329, benchmark: 5.284729 },
  { date: "2009-10-31", thorNet: -2.668544, benchmark: -3.699711 },
  { date: "2009-11-30", thorNet: 6.53841, benchmark: 5.540064 },
  { date: "2009-12-31", thorNet: 2.799613, benchmark: 4.610673 },
  { date: "2010-01-31", thorNet: -4.021016, benchmark: -3.317492 },
  { date: "2010-02-28", thorNet: 2.46708, benchmark: 4.190079 },
  { date: "2010-03-31", thorNet: 5.69563, benchmark: 7.22396 },
  { date: "2010-04-30", thorNet: 1.921837, benchmark: 2.65447 },
  { date: "2010-05-31", thorNet: -7.238435, benchmark: -7.368401 },
  { date: "2010-06-30", thorNet: -0.529354, benchmark: -6.307225 },
  { date: "2010-07-31", thorNet: 1.06977, benchmark: 7.354482 },
  { date: "2010-08-31", thorNet: -0.096676, benchmark: -4.756036 },
  { date: "2010-09-30", thorNet: 1.829771, benchmark: 10.18858 },
  { date: "2010-10-31", thorNet: 3.729088, benchmark: 3.562998 },
  { date: "2010-11-30", thorNet: 0.270868, benchmark: 0.820217 },
  { date: "2010-12-31", thorNet: 6.212486, benchmark: 7.215323 },
  { date: "2011-01-31", thorNet: 1.984833, benchmark: 2.113713 },
  { date: "2011-02-28", thorNet: 3.489906, benchmark: 4.015748 },
  { date: "2011-03-31", thorNet: 0.337993, benchmark: 0.832885 },
  { date: "2011-04-30", thorNet: 3.230652, benchmark: 3.131192 },
  { date: "2011-05-31", thorNet: -1.007088, benchmark: -0.614889 },
  { date: "2011-06-30", thorNet: -1.820094, benchmark: -1.803485 },
  { date: "2011-07-31", thorNet: -1.823181, benchmark: -3.615162 },
  { date: "2011-08-31", thorNet: -3.052796, benchmark: -6.353757 },
  { date: "2011-09-30", thorNet: 0.028961, benchmark: -9.050077 },
  { date: "2011-10-31", thorNet: 1.720538, benchmark: 13.06763 },
  { date: "2011-11-30", thorNet: -0.722519, benchmark: -0.87588 },
  { date: "2011-12-31", thorNet: 1.595928, benchmark: 0.156438 },
  { date: "2012-01-31", thorNet: 4.937871, benchmark: 5.682796 },
  { date: "2012-02-29", thorNet: 2.825588, benchmark: 4.007351 },
  { date: "2012-03-31", thorNet: 2.697256, benchmark: 2.319844 },
  { date: "2012-04-30", thorNet: -0.075404, benchmark: -0.75188 },
  { date: "2012-05-31", thorNet: -5.116699, benchmark: -6.993001 },
  { date: "2012-06-30", thorNet: 4.142539, benchmark: 3.85605 },
  { date: "2012-07-31", thorNet: 1.06347, benchmark: 0.121161 },
  { date: "2012-08-31", thorNet: 0.744672, benchmark: 3.065739 },
  { date: "2012-09-30", thorNet: 2.128209, benchmark: 2.514567 },
  { date: "2012-10-31", thorNet: -1.095891, benchmark: -0.824055 },
  { date: "2012-11-30", thorNet: 0.384999, benchmark: 1.275375 },
  { date: "2012-12-31", thorNet: 1.538583, benchmark: 2.271619 },
  { date: "2013-01-31", thorNet: 5.845367, benchmark: 6.507853 },
  { date: "2013-02-28", thorNet: 1.218752, benchmark: 0.968473 },
  { date: "2013-03-31", thorNet: 3.834663, benchmark: 4.364727 },
  { date: "2013-04-30", thorNet: 2.448644, benchmark: 1.693504 },
  { date: "2013-05-31", thorNet: 0.420908, benchmark: 2.687536 },
  { date: "2013-06-30", thorNet: -1.631155, benchmark: -1.231636 },
  { date: "2013-07-31", thorNet: 5.314283, benchmark: 5.63081 },
  { date: "2013-08-31", thorNet: -2.627488, benchmark: -2.920265 },
  { date: "2013-09-30", thorNet: 3.46501, benchmark: 4.112241 },
  { date: "2013-10-31", thorNet: 4.572304, benchmark: 4.279137 },
  { date: "2013-11-30", thorNet: 2.782537, benchmark: 2.220908 },
  { date: "2013-12-31", thorNet: 2.670888, benchmark: 2.881852 },
  { date: "2014-01-31", thorNet: -3.911368, benchmark: -2.961427 },
  { date: "2014-02-28", thorNet: 5.499481, benchmark: 5.336982 },
  { date: "2014-03-31", thorNet: 0.006792, benchmark: 0.607104 },
  { date: "2014-04-30", thorNet: 1.293864, benchmark: 0.383619 },
  { date: "2014-05-31", thorNet: 2.112198, benchmark: 2.156404 },
  { date: "2014-06-30", thorNet: 2.399679, benchmark: 2.85856 },
  { date: "2014-07-31", thorNet: -2.067929, benchmark: -2.333486 },
  { date: "2014-08-31", thorNet: 3.374117, benchmark: 4.204488 },
  { date: "2014-09-30", thorNet: -3.030336, benchmark: -2.584914 },
  { date: "2014-10-31", thorNet: 0.785638, benchmark: 3.021496 },
  { date: "2014-11-30", thorNet: 2.476912, benchmark: 2.663927 },
  { date: "2014-12-31", thorNet: 0.11908, benchmark: 0.279898 },
  { date: "2015-01-31", thorNet: 0.377852, benchmark: -2.920701 },
  { date: "2015-02-28", thorNet: 2.201646, benchmark: 5.723694 },
  { date: "2015-03-31", thorNet: -1.871819, benchmark: -0.95911 },
  { date: "2015-04-30", thorNet: 0.354879, benchmark: 0.407166 },
  { date: "2015-05-31", thorNet: 0.52607, benchmark: 0.724973 },
  { date: "2015-06-30", thorNet: -2.200729, benchmark: -2.268615 },
  { date: "2015-07-31", thorNet: 1.98977, benchmark: 0.964915 },
  { date: "2015-08-31", thorNet: -6.460003, benchmark: -5.461073 },
  { date: "2015-09-30", thorNet: -0.611049, benchmark: -3.014604 },
  { date: "2015-10-31", thorNet: 0.218022, benchmark: 6.987497 },
  { date: "2015-11-30", thorNet: -0.019348, benchmark: 0.30496 },
  { date: "2015-12-31", thorNet: -2.140422, benchmark: -2.476204 },
  { date: "2016-01-31", thorNet: 0.046825, benchmark: -5.558461 },
  { date: "2016-02-29", thorNet: -0.05355, benchmark: 0.994744 },
  { date: "2016-03-31", thorNet: 4.597821, benchmark: 7.979036 },
  { date: "2016-04-30", thorNet: 0.587809, benchmark: 1.247908 },
  { date: "2016-05-31", thorNet: 1.179816, benchmark: 1.358303 },
  { date: "2016-06-30", thorNet: 1.682608, benchmark: -0.063399 },
  { date: "2016-07-31", thorNet: 2.667567, benchmark: 4.144363 },
  { date: "2016-08-31", thorNet: -0.703885, benchmark: 0.155336 },
  { date: "2016-09-30", thorNet: -0.116425, benchmark: 0.103004 },
  { date: "2016-10-31", thorNet: -2.422867, benchmark: -2.440487 },
  { date: "2016-11-30", thorNet: 6.003384, benchmark: 5.236014 },
  { date: "2016-12-31", thorNet: 1.367141, benchmark: 1.125747 },
  { date: "2017-01-31", thorNet: 1.809705, benchmark: 2.008308 },
  { date: "2017-02-28", thorNet: 2.630099, benchmark: 3.134189 },
  { date: "2017-03-31", thorNet: -0.164064, benchmark: 0.020944 },
  { date: "2017-04-30", thorNet: 0.986201, benchmark: 0.660643 },
  { date: "2017-05-31", thorNet: 1.489074, benchmark: 0.557859 },
  { date: "2017-06-30", thorNet: 1.001923, benchmark: 1.163723 },
  { date: "2017-07-31", thorNet: 1.852762, benchmark: 1.596902 },
  { date: "2017-08-31", thorNet: 0.773413, benchmark: -0.9983 },
  { date: "2017-09-30", thorNet: 1.809642, benchmark: 2.934013 },
  { date: "2017-10-31", thorNet: 2.737413, benchmark: 1.088557 },
  { date: "2017-11-30", thorNet: 2.89616, benchmark: 3.799955 },
  { date: "2017-12-31", thorNet: 0.833679, benchmark: 1.238358 },
  { date: "2018-01-31", thorNet: 5.971083, benchmark: 4.384835 },
  { date: "2018-02-28", thorNet: -6.470328, benchmark: -4.390307 },
  { date: "2018-03-31", thorNet: -0.01694, benchmark: -0.926179 },
  { date: "2018-04-30", thorNet: 0.367415, benchmark: 0.371948 },
  { date: "2018-05-31", thorNet: 0.590925, benchmark: 1.452193 },
  { date: "2018-06-30", thorNet: 0.101894, benchmark: 0.971994 },
  { date: "2018-07-31", thorNet: -0.281191, benchmark: 3.101368 },
  { date: "2018-08-31", thorNet: 1.577001, benchmark: 1.960967 },
  { date: "2018-09-30", thorNet: 0.498945, benchmark: 0.171373 },
  { date: "2018-10-31", thorNet: -4.606011, benchmark: -7.246507 },
  { date: "2018-11-30", thorNet: 1.133462, benchmark: 2.614314 },
  { date: "2018-12-31", thorNet: -4.660057, benchmark: -9.53738 },
  { date: "2019-01-31", thorNet: 6.332349, benchmark: 9.814022 },
  { date: "2019-02-28", thorNet: 2.877229, benchmark: 3.666425 },
  { date: "2019-03-31", thorNet: 1.985247, benchmark: 0.834819 },
  { date: "2019-04-30", thorNet: 2.599284, benchmark: 3.590575 },
  { date: "2019-05-31", thorNet: -5.638537, benchmark: -6.932276 },
  { date: "2019-06-30", thorNet: 6.429259, benchmark: 7.5518 },
  { date: "2019-07-31", thorNet: 1.059282, benchmark: 0.844134 },
  { date: "2019-08-31", thorNet: -1.032451, benchmark: -3.265566 },
  { date: "2019-09-30", thorNet: 1.268656, benchmark: 3.269459 },
  { date: "2019-10-31", thorNet: 1.017834, benchmark: 1.230572 },
  { date: "2019-11-30", thorNet: 1.947721, benchmark: 3.400046 },
  { date: "2019-12-31", thorNet: 2.80934, benchmark: 2.704938 },
  { date: "2020-01-31", thorNet: -0.68932, benchmark: -1.883844 },
  { date: "2020-02-29", thorNet: -6.129937, benchmark: -8.869114 },
  { date: "2020-03-31", thorNet: 6.257682, benchmark: -17.970521 },
  { date: "2020-04-30", thorNet: 11.039538, benchmark: 14.425131 },
  { date: "2020-05-31", thorNet: 2.549035, benchmark: 4.753494 },
  { date: "2020-06-30", thorNet: 1.79686, benchmark: 1.460954 },
  { date: "2020-07-31", thorNet: 5.346203, benchmark: 4.992155 },
  { date: "2020-08-31", thorNet: 4.19541, benchmark: 4.268065 },
  { date: "2020-09-30", thorNet: -4.230458, benchmark: -2.501041 },
  { date: "2020-10-31", thorNet: -2.702921, benchmark: -0.554974 },
  { date: "2020-11-30", thorNet: 6.299991, benchmark: 14.296357 },
  { date: "2020-12-31", thorNet: 2.86813, benchmark: 4.157614 },
  { date: "2021-01-31", thorNet: -0.112696, benchmark: -0.815411 },
  { date: "2021-02-28", thorNet: 2.581871, benchmark: 6.086951 },
  { date: "2021-03-31", thorNet: 4.76363, benchmark: 6.045988 },
  { date: "2021-04-30", thorNet: 5.121383, benchmark: 4.673166 },
  { date: "2021-05-31", thorNet: 0.757924, benchmark: 1.9153 },
  { date: "2021-06-30", thorNet: -0.726248, benchmark: 0.023256 },
  { date: "2021-07-31", thorNet: 3.114132, benchmark: 1.293731 },
  { date: "2021-08-31", thorNet: 2.351311, benchmark: 2.370979 },
  { date: "2021-09-30", thorNet: -4.695512, benchmark: -3.79048 },
  { date: "2021-10-31", thorNet: 4.976557, benchmark: 5.299675 },
  { date: "2021-11-30", thorNet: -1.130935, benchmark: -2.643254 },
  { date: "2021-12-31", thorNet: 5.14132, benchmark: 6.274414 },
  { date: "2022-01-31", thorNet: -3.044912, benchmark: -4.368664 },
  { date: "2022-02-28", thorNet: -1.372334, benchmark: -0.893081 },
  { date: "2022-03-31", thorNet: 1.612193, benchmark: 2.671681 },
  { date: "2022-04-30", thorNet: -5.82095, benchmark: -6.505611 },
  { date: "2022-05-31", thorNet: -0.708051, benchmark: 1.003724 },
  { date: "2022-06-30", thorNet: -5.443765, benchmark: -9.392651 },
  { date: "2022-07-31", thorNet: 3.192751, benchmark: 8.649348 },
  { date: "2022-08-31", thorNet: -2.836766, benchmark: -3.483246 },
  { date: "2022-09-30", thorNet: -2.908273, benchmark: -9.167024 },
  { date: "2022-10-31", thorNet: 4.815742, benchmark: 9.648028 },
  { date: "2022-11-30", thorNet: 6.246645, benchmark: 6.635128 },
  { date: "2022-12-31", thorNet: -4.170215, benchmark: -4.693956 },
  { date: "2023-01-31", thorNet: 3.540693, benchmark: 7.419477 },
  { date: "2023-02-28", thorNet: -2.522678, benchmark: -3.381022 },
  { date: "2023-03-31", thorNet: -0.425132, benchmark: -0.860341 },
  { date: "2023-04-30", thorNet: -0.038773, benchmark: 0.359565 },
  { date: "2023-05-31", thorNet: -3.325588, benchmark: -3.810122 },
  { date: "2023-06-30", thorNet: 6.629502, benchmark: 7.653012 },
  { date: "2023-07-31", thorNet: 3.153178, benchmark: 3.501746 },
  { date: "2023-08-31", thorNet: -2.831305, benchmark: -3.202494 },
  { date: "2023-09-30", thorNet: -3.501039, benchmark: -5.078524 },
  { date: "2023-10-31", thorNet: -1.10895, benchmark: -4.135798 },
  { date: "2023-11-30", thorNet: 3.222798, benchmark: 9.180576 },
  { date: "2023-12-31", thorNet: 5.525402, benchmark: 6.821741 },
  { date: "2024-01-31", thorNet: -1.590991, benchmark: -0.849187 },
  { date: "2024-02-29", thorNet: 4.285092, benchmark: 4.045758 },
  { date: "2024-03-31", thorNet: 3.650582, benchmark: 4.473022 },
  { date: "2024-04-30", thorNet: -4.512345, benchmark: -4.823767 },
  { date: "2024-05-31", thorNet: 3.015683, benchmark: 2.841215 },
  { date: "2024-06-30", thorNet: -1.726973, benchmark: -0.508098 },
  { date: "2024-07-31", thorNet: 2.966755, benchmark: 4.455773 },
  { date: "2024-08-31", thorNet: 3.920547, benchmark: 2.488318 },
  { date: "2024-09-30", thorNet: 2.516018, benchmark: 2.269135 },
  { date: "2024-10-31", thorNet: -2.838255, benchmark: -1.601913 },
  { date: "2024-11-30", thorNet: 4.089402, benchmark: 6.426919 },
  { date: "2024-12-31", thorNet: -7.392727, benchmark: -6.275467 },
  { date: "2025-01-31", thorNet: 1.999839, benchmark: 3.429779 },
  { date: "2025-02-28", thorNet: -0.491526, benchmark: -0.584859 },
  { date: "2025-03-31", thorNet: -2.894995, benchmark: -3.40261 },
  { date: "2025-04-30", thorNet: 5.483292, benchmark: -2.361034 },
  { date: "2025-05-31", thorNet: 5.768309, benchmark: 4.31003 },
  { date: "2025-06-30", thorNet: 4.149661, benchmark: 3.426125 },
  { date: "2025-07-31", thorNet: 1.883093, benchmark: 1.039935 },
  { date: "2025-08-31", thorNet: 2.535648, benchmark: 2.717456 },
  { date: "2025-09-30", thorNet: 1.811315, benchmark: 1.010198 },
  { date: "2025-10-31", thorNet: 0.074647, benchmark: -0.933045 },
  { date: "2025-11-30", thorNet: -0.213747, benchmark: 1.915626 },
  { date: "2025-12-31", thorNet: -0.50861, benchmark: 0.410316 },
  { date: "2026-01-31", thorNet: 5.540055, benchmark: 3.403608 },
  { date: "2026-02-28", thorNet: 6.06, benchmark: 3.4784 },
  { date: "2026-03-31", thorNet: -4.122366, benchmark: -5.96593 },
  { date: "2026-04-30", thorNet: 0.440606, benchmark: 6.002503 },
  { date: "2026-05-31", thorNet: 1.850338, benchmark: 2.649429 },
];

// ─── Helper functions ───

function compoundReturns(returns: number[]): number {
  let cumulative = 1;
  for (const r of returns) {
    cumulative *= 1 + r / 100;
  }
  return (cumulative - 1) * 100;
}

function annualizeReturn(totalReturnPct: number, months: number): number {
  const totalFactor = 1 + totalReturnPct / 100;
  const annualized = Math.pow(totalFactor, 12 / months) - 1;
  return annualized * 100;
}

// ─── Standard Period Returns ───
// All periods are derived from the END of the series (the as-of month):
// MTD = the as-of month; QTD/YTD = calendar quarter/year to the as-of month;
// trailing periods use exact 12/36/60/120-month windows.

function calcStandardPeriods() {
  const data = monthlyReturns;
  const lastDate = data[data.length - 1].date;
  const year = lastDate.slice(0, 4);
  const month = Number(lastDate.slice(5, 7));
  const quarterStartMonth = Math.floor((month - 1) / 3) * 3 + 1;
  const quarterStart = `${year}-${String(quarterStartMonth).padStart(2, "0")}-01`;
  const yearStart = `${year}-01-01`;

  const inPeriod = (start: string) => data.filter((d) => d.date >= start);

  const mtd = {
    thor: data[data.length - 1].thorNet,
    bench: data[data.length - 1].benchmark,
  };
  const qtd = {
    thor: compoundReturns(inPeriod(quarterStart).map((d) => d.thorNet)),
    bench: compoundReturns(inPeriod(quarterStart).map((d) => d.benchmark)),
  };
  const ytd = {
    thor: compoundReturns(inPeriod(yearStart).map((d) => d.thorNet)),
    bench: compoundReturns(inPeriod(yearStart).map((d) => d.benchmark)),
  };

  const oneYear = {
    thor: compoundReturns(data.slice(-12).map((d) => d.thorNet)),
    bench: compoundReturns(data.slice(-12).map((d) => d.benchmark)),
  };

  const threeYear = {
    thor: annualizeReturn(compoundReturns(data.slice(-36).map((d) => d.thorNet)), 36),
    bench: annualizeReturn(compoundReturns(data.slice(-36).map((d) => d.benchmark)), 36),
  };

  const fiveYear = {
    thor: annualizeReturn(compoundReturns(data.slice(-60).map((d) => d.thorNet)), 60),
    bench: annualizeReturn(compoundReturns(data.slice(-60).map((d) => d.benchmark)), 60),
  };

  const tenYear = {
    thor: annualizeReturn(compoundReturns(data.slice(-120).map((d) => d.thorNet)), 120),
    bench: annualizeReturn(compoundReturns(data.slice(-120).map((d) => d.benchmark)), 120),
  };

  const sinceInception = {
    thor: annualizeReturn(compoundReturns(data.map((d) => d.thorNet)), data.length),
    bench: annualizeReturn(compoundReturns(data.map((d) => d.benchmark)), data.length),
  };

  return {
    mtd,
    qtd,
    ytd,
    oneYear,
    threeYear,
    fiveYear,
    tenYear,
    sinceInception,
  };
}

// ─── Calendar Year Returns ───

function calcCalendarYears() {
  const years = Array.from(new Set(monthlyReturns.map((d) => d.date.slice(0, 4)))).sort();
  return years.map((yearStr) => {
    const yearData = monthlyReturns.filter((d) => d.date.startsWith(`${yearStr}-`));
    return {
      year: Number(yearStr),
      thor: compoundReturns(yearData.map((d) => d.thorNet)),
      bench: compoundReturns(yearData.map((d) => d.benchmark)),
    };
  });
}

// ─── Growth of $10,000 ───

function calcGrowthOf10K() {
  let thorValue = 10000;
  let benchValue = 10000;

  for (const m of monthlyReturns) {
    thorValue *= 1 + m.thorNet / 100;
    benchValue *= 1 + m.benchmark / 100;
  }

  return {
    thor: Math.round(thorValue),
    bench: Math.round(benchValue),
  };
}

// ─── Risk Statistics ───

function calcRiskStats() {
  const thorReturns = monthlyReturns.map((d) => d.thorNet);
  const benchReturns = monthlyReturns.map((d) => d.benchmark);
  const n = thorReturns.length;

  const thorCumulative = compoundReturns(thorReturns);
  const benchCumulative = compoundReturns(benchReturns);
  const thorAnnReturn = annualizeReturn(thorCumulative, n);
  const benchAnnReturn = annualizeReturn(benchCumulative, n);

  const thorMean = thorReturns.reduce((a, b) => a + b, 0) / n;
  const benchMean = benchReturns.reduce((a, b) => a + b, 0) / n;
  const thorMonthlyStd = Math.sqrt(thorReturns.reduce((sum, r) => sum + (r - thorMean) ** 2, 0) / (n - 1));
  const benchMonthlyStd = Math.sqrt(benchReturns.reduce((sum, r) => sum + (r - benchMean) ** 2, 0) / (n - 1));
  const thorAnnStd = thorMonthlyStd * Math.sqrt(12);
  const benchAnnStd = benchMonthlyStd * Math.sqrt(12);

  // Sharpe Ratio (risk-free = 2% long-term average)
  const riskFree = 2.0;
  const thorSharpe = (thorAnnReturn - riskFree) / thorAnnStd;
  const benchSharpe = (benchAnnReturn - riskFree) / benchAnnStd;

  function maxDrawdown(returns: number[]): number {
    let peak = 1;
    let cumulative = 1;
    let maxDD = 0;
    for (const r of returns) {
      cumulative *= 1 + r / 100;
      if (cumulative > peak) peak = cumulative;
      const dd = (cumulative - peak) / peak;
      if (dd < maxDD) maxDD = dd;
    }
    return maxDD * 100;
  }

  const thorMaxDD = maxDrawdown(thorReturns);
  const benchMaxDD = maxDrawdown(benchReturns);

  const thorBest = Math.max(...thorReturns);
  const thorWorst = Math.min(...thorReturns);
  const benchBest = Math.max(...benchReturns);
  const benchWorst = Math.min(...benchReturns);

  const thorPositive = (thorReturns.filter((r) => r > 0).length / n) * 100;
  const benchPositive = (benchReturns.filter((r) => r > 0).length / n) * 100;

  return {
    annualizedReturn: { thor: thorAnnReturn, bench: benchAnnReturn },
    annualizedStdDev: { thor: thorAnnStd, bench: benchAnnStd },
    sharpeRatio: { thor: thorSharpe, bench: benchSharpe },
    maxDrawdown: { thor: thorMaxDD, bench: benchMaxDD },
    bestMonth: { thor: thorBest, bench: benchBest },
    worstMonth: { thor: thorWorst, bench: benchWorst },
    positiveMonths: { thor: thorPositive, bench: benchPositive },
  };
}

// ─── Export all computed data ───

export const standardPeriods = calcStandardPeriods();
export const calendarYears = calcCalendarYears();
export const growthOf10K = calcGrowthOf10K();
export const riskStats = calcRiskStats();
